(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"REV659_Wave2_Awareness_320x50_atlas_1", frames: [[0,0,810,456],[0,458,1000,300]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._300x600A1_CA_WHT = function() {
	this.initialize(ss["REV659_Wave2_Awareness_320x50_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.plateHL2 = function() {
	this.initialize(ss["REV659_Wave2_Awareness_320x50_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.RevivierLogorevsvg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// RevivierLogo_rev_svg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AByCaQgGAAgCgCIgFgEIhtiRIBCAAQAXAAAJgJQAJgJAAgUIAAgSQAAgUgJgKQgJgJgXAAIiiAAQgFAAAAAFIAADnQAAAKgKAAIgvAAQgLAAAAgKIAAkbQAAgOAOAAIDrAAQAzAAAWAXQAWAXAAAtIAAAZQAAAlgQAVQgPAWgjAHIBLBcIAAABQADACgCAEQAAAFgHAAg");
	this.shape.setTransform(253.9281,15.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABxCaQgFAAgDgCIgEgEIhuiRIBDAAQAWAAAKgJQAJgJAAgUIAAgSQAAgUgJgKQgKgJgWAAIiiAAQgGAAAAAFIAADnQAAAKgJAAIgwAAQgKAAAAgKIAAkbQAAgOANAAIDsAAQAyAAAWAXQAWAXAAAtIAAAZQAAAlgPAVQgPAWgjAHIBLBcIAAABQACACgBAEQAAAFgHAAg");
	this.shape_1.setTransform(17.755,15.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnCaQghAAgYgGQgZgHgNgNQgOgOgIgWQgHgVAAghIAAhLQAAgfAHgWQAIgWAOgOQAPgOAXgGQAXgHAiAAIDAAAQALAAAAAKIAAAqQAAAJgLAAIi/AAQgRAAgLADQgMAEgGAGQgGAGgEAMQgCAOAAAPIAAAEID3AAQAKAAAAAKIAAAiQAAAJgKAAIj3AAIAAAIQAAAPACAOQAEAMAGAGQAGAGAMAEQALADARAAIC/AAQALAAAAAJIAAAqQAAAKgLAAg");
	this.shape_2.setTransform(210.5,15.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJCZQgRAAgLgGQgMgIgKgTIiTkHQgCgDABgEQACgCAFgBIA4AAIAGABIAEAFICBDrQACAEADgBIABAAQADABACgEIB/jrQADgFAHgBIA6AAQAFABACACQABADgDAEIiQEHQgKAUgMAHQgKAGgOAAg");
	this.shape_3.setTransform(167.4726,15.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXCZQgKAAAAgJIAAkfQAAgKAKAAIAvAAQAKAAAAAKIAAEfQAAAJgKAAg");
	this.shape_4.setTransform(135.3,15.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJCZQgRAAgLgGQgMgIgKgTIiSkHQgDgDABgEQACgCAFgBIA4AAIAGABIAEAFICBDrQACAEADgBIABAAQAEABABgEIB/jrQADgFAIgBIA5AAQAFABACACQABADgDAEIiQEHQgLAUgLAHQgKAGgOAAg");
	this.shape_5.setTransform(103.125,15.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnCaQghAAgYgGQgZgHgNgNQgOgOgIgWQgHgVAAghIAAhLQAAgfAHgWQAIgWAOgOQAPgOAXgGQAXgHAiAAIDAAAQALAAAAAKIAAAqQAAAJgLAAIi/AAQgRAAgLADQgLADgHAHQgGAGgEAMQgCAOAAAPIAAAEID3AAQAKAAAAAKIAAAiQAAAJgKAAIj3AAIAAAIQAAAPACAOQAEAMAGAGQAGAGAMAEQALADARAAIC/AAQALAAAAAJIAAAqQAAAKgLAAg");
	this.shape_6.setTransform(57.95,15.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAJASIAAgUIgHANIgDAAIgHgNIAAAUIgIAAIAAgkIAHAAIAJAUIAKgUIAHAAIAAAkg");
	this.shape_7.setTransform(282.425,2.15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDASIAAgdIgJAAIAAgHIAZAAIAAAHIgKAAIAAAdg");
	this.shape_8.setTransform(278.875,2.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgaAyIAAhjIA1AAIAAALIgoAAIAAAhIAkAAIAAAKIgkAAIAAAiIAoAAIAAALg");
	this.shape_9.setTransform(267.3,47.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAyIAAhYIgbAAIAAgLIBDAAIAAALIgbAAIAABYg");
	this.shape_10.setTransform(253.725,47.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAeAyIgIgXIgrAAIgIAXIgOAAIAlhiIAOAAIAkBigAgRARIAjAAIgSgxg");
	this.shape_11.setTransform(239.125,47.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXAyIAAhjIANAAIAABYIAiAAIAAALg");
	this.shape_12.setTransform(225.7,47.025);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AghAyIAAhjIAhAAQARAAAIAIQAJAJAAAMQAAANgJAHQgIAIgRAAIgTAAIAAAqgAgTgBIATAAQAJAAAGgFQAGgFgBgJQAAgSgUAAIgTAAg");
	this.shape_13.setTransform(212.45,47.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaAyIAAhjIA1AAIAAALIgoAAIAAAhIAkAAIAAAKIgkAAIAAAiIAoAAIAAALg");
	this.shape_14.setTransform(188.85,47.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgQAwQgIgDgFgHQgEgHAAgHIAOAAQABAHAFAFQAFAEAIAAQALAAAEgEQAGgGAAgGQAAgGgDgEQgDgDgFgCIgMgEIgQgFQgHgCgEgFQgDgGAAgJQAAgJADgGQAEgGAIgEQAJgDAIAAQAOAAAJAHQAJAHABAMIgOAAQgBgGgFgFQgGgEgIAAQgIAAgFAEQgFAFAAAHQAAAGADADQACADAFACIANAEIAQAFQAFACAFAGQAFAGgBAJQAAAHgDAHQgEAGgIAEQgJAEgKAAQgHAAgJgDg");
	this.shape_15.setTransform(174.95,46.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAbAyIg1hPIAABPIgNAAIAAhjIANAAIA1BPIAAhPIANAAIAABjg");
	this.shape_16.setTransform(159.775,47);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaAyIAAhjIA1AAIAAALIgoAAIAAAhIAkAAIAAAKIgkAAIAAAiIAoAAIAAALg");
	this.shape_17.setTransform(145.275,47.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgXAtQgMgHgGgLQgHgMAAgOQAAgNAHgNQAGgLAMgHQALgHAOAAQARAAAMAIQAMAHAGAPIgQAAQgEgJgIgEQgHgFgMgBQgKABgIAFQgIAEgFAJQgFAKAAAKQAAALAFAKQAEAIAJAGQAKAFAIAAQAKAAAJgFQAIgFAEgJIAQAAQgGAOgMAJQgNAHgQAAQgOAAgLgGg");
	this.shape_18.setTransform(129.925,47);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgGAyIAAhjIANAAIAABjg");
	this.shape_19.setTransform(116.825,47.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgXAyIAAhjIANAAIAABYIAiAAIAAALg");
	this.shape_20.setTransform(106.525,47.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgXAyIAAhjIANAAIAABYIAiAAIAAALg");
	this.shape_21.setTransform(84.775,47.025);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAeAyIgIgXIgrAAIgJAXIgNAAIAlhiIANAAIAlBigAgSARIAkAAIgSgxg");
	this.shape_22.setTransform(70.55,47.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgFAyIAAhYIgcAAIAAgLIBDAAIAAALIgcAAIAABYg");
	this.shape_23.setTransform(55.9,47.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgGAyIAAhjIANAAIAABjg");
	this.shape_24.setTransform(44.4,47.025);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgYAtQgMgIgHgKQgGgMAAgPQAAgOAGgLQAHgMAMgGQAMgHAMAAQARAAAMAIQAMAIAGAOIgQAAQgEgJgIgEQgIgFgLAAQgJAAgJAFQgIAFgFAIQgFAJAAALQAAAMAFAJQAFAIAIAGQAJAEAJAAQAQAAAJgJQAJgJACgOIgnAAIAAgKIA1AAIAAAJQgBANgHAKQgHAKgKAGQgLAGgOAAQgLAAgNgGg");
	this.shape_25.setTransform(31.175,47);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgGAyIAAhjIANAAIAABjg");
	this.shape_26.setTransform(17.925,47.025);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgqAyIAAhjIAgAAQAQAAALAGQANAHAGALQAGALABAOQgBAQgGALQgGALgNAGQgKAGgRAAgAgcAnIASAAQATAAAJgKQALgKAAgTQAAgRgLgLQgJgKgTAAIgSAAg");
	this.shape_27.setTransform(5.45,47.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,284.1,52.1);


(lib.PLATE = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib._300x600A1_CA_WHT();
	this.instance.setTransform(-405,-228);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.PLATE, new cjs.Rectangle(-405,-228,810,456), null);


(lib.HL = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.plateHL2();
	this.instance.setTransform(177.95,-245,0.1779,1.6333,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HL, new cjs.Rectangle(0.1,-245,177.9,490), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkvEYIAAjSIAkAAIAAAVQAGgKANgGQAMgHAQAAQARAAAPAJQAPAJAIAQQAKARgBAWQABAWgKARQgIARgPAIQgPAKgRAAQgQAAgMgGQgMgHgHgKIAABYgAj4BpQgJAFgFAKQgGAJABAMQgBAOAGAJQAFAKAJAEQAIAGAKgBQAKAAAJgFQAIgFAFgJQAGgKAAgNQAAgNgGgJQgFgJgIgGQgJgEgKAAQgKAAgIAFgAQ1DNQgRgIgJgRQgJgQAAgXQAAgVAJgRQAJgRAQgJQAQgJAVAAQAUAAAQAJQAQAIAKARQAIAPAAAVIgBAPIhoAAQABAPAKAIQAKAJANAAQAUAAAJgRIAmAAQgFAUgSANQgSAOgZAAQgVAAgPgKgAR6CAQAAgNgKgJQgKgJgOAAQgNAAgJAJQgKAIgCAOIBEAAIAAAAgAM9DNQgRgIgIgRQgJgQAAgXQAAgVAJgRQAIgRAQgJQARgJAVAAQAUAAAQAJQAQAIAJARQAJAPgBAVIgBAPIhnAAQABAPAKAIQAJAJAOAAQAUAAAJgRIAmAAQgGAUgSANQgRAOgZAAQgVAAgQgKgAOCCAQAAgNgKgJQgKgJgOAAQgMAAgKAJQgJAIgCAOIBDAAIAAAAgAHeDRQgOgHgIgKQgIgMgBgNIAkAAQABAJAHAFQAHAGALgBQAKAAAGgDQAFgEAAgHQAAgHgGgDQgIgEgPgEQgQgEgKgEQgKgEgIgJQgGgIgBgOQAAgMAHgJQAHgKAMgGQANgGASAAQAZAAAPANQAPAMACAWIgjAAQgBgJgGgEQgGgFgKgBQgLAAgEAFQgGADAAAHQAAAGAHAEQAHAEAQAEQAPADAKAFQAKAEAHAIQAIAJAAAOQAAAMgHAKQgHAJgNAGQgMAGgRAAQgSAAgNgGgADTDNQgRgIgJgRQgJgQAAgXQAAgVAJgRQAJgRAQgJQAQgJAVAAQAVAAAQAJQAPAIAKARQAIAPAAAVIgBAPIhoAAQABAPAKAIQAJAJAPAAQATAAAJgRIAmAAQgGAUgRANQgRAOgaAAQgUAAgQgKgAEYCAQAAgNgKgJQgKgJgOAAQgNAAgJAJQgKAIgCAOIBEAAIAAAAgAgyDNQgPgIgJgRQgIgRAAgWQAAgWAIgQQAJgRAPgJQAPgJASAAQAQAAAKAHQAMAGAIAKIAAgVIAkAAIAACOIgkAAIAAgUQgIAKgMAGQgKAHgRAAQgSAAgOgKgAgbBoQgIAGgFAJQgFAJgBANQABANAFAKQAFAJAIAFQAJAFAKAAQAJABAIgGQAKgEAEgKQAFgJABgOQgBgNgFgJQgEgJgKgFQgIgFgJAAQgKAAgJAEgAnjDNQgRgIgIgRQgKgQABgXQgBgVAKgRQAIgRARgJQAPgJAWAAQAUAAAQAJQAQAIAJARQAJAPgBAVIgBAPIhnAAQABAPAJAIQAKAJAOAAQAUAAAJgRIAmAAQgGAUgSANQgRAOgZAAQgVAAgQgKgAmeCAQAAgNgKgJQgKgJgNAAQgNAAgKAJQgJAIgCAOIBDAAIAAAAgApqDRQgOgHgIgKQgIgMgBgNIAkAAQABAJAHAFQAHAGAKgBQALAAAGgDQAFgEAAgHQAAgHgGgDQgIgEgPgEQgQgEgKgEQgKgEgIgJQgGgIAAgOQgBgMAHgJQAHgKAMgGQAOgGARAAQAZAAAPANQAPAMABAWIgiAAQgBgJgGgEQgGgFgKgBQgLAAgFAFQgFADAAAHQAAAGAHAEQAIAEAPAEQAPADAKAFQAKAEAHAIQAIAJAAAOQAAAMgHAKQgHAJgNAGQgMAGgRAAQgSAAgNgGgAuiDNQgQgIgJgRQgJgQAAgXQAAgVAJgRQAJgRAQgJQAQgJAVAAQAUAAAQAJQAQAIAKARQAIAPAAAVIgBAPIhoAAQABAPAKAIQAKAJAOAAQATAAAJgRIAmAAQgFAUgSANQgSAOgZAAQgVAAgQgKgAtcCAQAAgNgKgJQgKgJgOAAQgNAAgJAJQgKAIgCAOIBEAAIAAAAgAw1DNQgQgIgJgRQgJgQAAgXQAAgVAJgRQAJgRAQgJQAQgJAUAAQAbAAARAOQARANAGAYIgmAAQgEgKgHgFQgHgFgLAAQgPAAgJALQgKALABAUQgBAVAKALQAJALAPAAQAVAAAIgTIAmAAQgGAXgSANQgRAOgaAAQgUAAgQgKgASyDQQgGgGAAgJQAAgIAGgHQAHgGAJAAQAKAAAFAGQAHAHAAAIQAAAJgHAGQgFAHgKgBQgJABgHgHgAO6DUIAAiOIAkAAIAAAXQAIgMAKgGQAMgGAOgBIAAAmIgKAAQgQAAgJAIQgJAIAAAUIAABGgALlDUIAAhOQAAgRgJgJQgIgJgPAAQgPAAgIAJQgJAJAAARIAABOIgkAAIAAi9IAkAAIAABBQAHgJAMgFQALgGAOAAQAQAAANAIQAMAHAIANQAGAOABATIAABTgAGGDUIAAiOIAkAAIAACOgACQDUQgtABAAgtIAAhEIgRAAIAAgeIARAAIAAgiIAkAAIAAAiIAgAAIAAAeIggAAIAABEQAAAIAEADQADADAIAAIARAAIAAAegAiJDUIAAi9IAkAAIAAC9gArBDUIAAhOQAAgRgIgJQgJgJgOAAQgPAAgIAJQgJAJAAARIAABOIgkAAIAAiOIAkAAIAAASQAHgJALgFQAMgGANAAQAZABAQAPQAPAQABAdIAABTgAyODUIAAiOIAkAAIAACOgAzODUIAAi9IAkAAIAAC9gAGIAwQgFgHgBgJQABgIAFgGQAHgHAKABQAJgBAGAHQAGAGAAAIQAAAJgGAHQgGAFgJABQgKgBgHgFgAyMAwQgFgHgBgJQABgIAFgGQAHgHAKABQAJgBAGAHQAGAGAAAIQAAAJgGAHQgGAFgJABQgKgBgHgFgAnYgWQgTgOgDgYIAjAAQAEAJAJAGQAJAFANAAQAQABAKgKQAJgJAAgTIAAgWQgGAKgNAGQgLAIgQgBQgSAAgPgJQgPgJgIgRQgJgRAAgVQAAgWAJgQQAIgSAPgIQAPgKASABQAQAAALAGQANAGAGAKIAAgUIAlAAIAACPQAAAUgIAQQgIAPgQAJQgQAJgXAAQgdAAgUgOgAm8i6QgJAFgFAJQgGAKABANQgBAMAGAKQAFAKAJAEQAJAGAJAAQAKAAAIgFQAKgFAFgKQAEgJAAgNQAAgNgEgKQgFgIgKgFQgIgFgKgBQgKAAgIAFgAiRhVQgPgJgIgRQgJgRAAgVQAAgWAJgQQAIgSAPgIQAPgKASABQAPAAANAGQALAHAHAJIAAgUIAlAAIAACOIglAAIAAgVQgHAKgLAGQgNAIgPgBQgTAAgOgJgAh5i6QgJAFgFAJQgGAKABANQgBAMAGAKQAFAKAJAEQAIAGAKAAQAKAAAJgFQAJgFAEgKQAGgJgBgNQABgNgGgKQgEgIgJgFQgJgFgKgBQgKAAgIAFgAq6hVQgPgJgJgRQgJgRAAgVQAAgWAJgQQAJgSAPgIQAPgKARABQAOAAANAFQAMAHAIAKIAAhDIAlAAIAAC9IglAAIAAgVQgHAKgMAHQgMAGgQAAQgRAAgPgJgAqji6QgJAFgEAJQgGAKAAANQAAAMAGAKQAEAKAJAEQAJAGAJAAQAKAAAJgFQAJgFAFgKQAFgJAAgNQAAgNgFgKQgFgIgJgFQgJgFgKgBQgJAAgJAFgAuFhVQgRgJgJgRQgIgQgBgWQABgWAIgQQAKgSAPgIQARgKAUABQAVgBAQAKQAQAIAJAQQAIAQAAAVIAAAOIhoAAQABAPAKAJQAJAJAOAAQAUgBAIgQIAnAAQgGAUgSANQgRANgaAAQgUAAgQgJgAs/ijQgBgNgJgIQgLgJgOAAQgNAAgIAJQgKAIgCANIBEAAIAAAAgAgChOIAAi9IAjAAIAAC9gAjRhOQgtAAAAgsIAAhFIgRAAIAAgdIARAAIAAgjIAkAAIAAAjIAgAAIAAAdIggAAIAABFQAAAIADACQAEADAIAAIARAAIAAAfgAlFhOIAAiOIAkAAIAACOgAorhOIAAiOIAkAAIAACOgAvehOIAAhPQABgQgJgKQgJgIgOgBQgPABgJAIQgIAKAAAQIAABPIgkAAIAAi9IAkAAIAABBQAHgKALgFQAMgFAOAAQAQAAANAHQAMAHAIAOQAGANAAAUIAABTgAynhOIAAiWIgwAAIAAgdICDAAIAAAdIgwAAIAACWgAlCjzQgGgGAAgJQAAgJAGgGQAGgGAKAAQAJAAAGAGQAHAGAAAJQAAAJgHAGQgGAGgJAAQgKAAgGgGgAoojzQgHgGAAgJQAAgJAHgGQAGgGAKAAQAJAAAGAGQAGAGAAAJQAAAJgGAGQgGAGgJAAQgKAAgGgGg");
	this.shape.setTransform(128.15,40.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(4.2,12.2,248,56), null);


(lib.HEAD1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABEGTQglgbgFguIBEAAQAFATASALQARALAaAAQAeAAASgSQASgSAAgkIAAgqQgNATgXANQgXANgdAAQgjAAgbgSQgdgRgQggQgRggABgpQgBgpARggQAQgfAcgRQAcgRAjAAQAeAAAWAMQAXAMANATIAAgnIBFAAIAAEPQgBAmgPAdQgOAdgfARQgeASgrAAQg5AAgkgbgAB4BdQgQAJgKASQgKARAAAZQAAAYAKASQAKATAQAJQAQAKASAAQAUAAAQgJQARgKAJgSQAKgSAAgYQAAgZgKgSQgJgRgRgKQgQgJgUAAQgSAAgQAJgAPsEcQgdgRgQggQgQgggBgpQABgpAQggQAQgfAdgRQAcgRAiAAQAaAAAYALQAYAMANATIAAh/IBFAAIAAFmIhFAAIAAgoQgMAUgWAMQgYANgdAAQgjAAgbgSgAQYBdQgQAJgKASQgKARAAAZQAAAYAKASQAKATAQAJQAQAKATAAQASAAASgJQAQgKAJgSQALgSAAgYQAAgZgLgSQgJgRgQgKQgSgJgSAAQgTAAgQAJgALDEcQgggRgSgfQgRggAAgpQAAgpASggQASggAggRQAggRAnAAQAmAAAgARQAgARARAgQATAgAAApQAAApgTAgQgSAfghARQgfASgnAAQgnAAgfgSgALYBoQgTAUAAAnQAAAmATAVQATAUAeAAQASAAAQgJQARgJAJgSQAKgSAAgZQAAgngVgUQgTgVgdAAQgeAAgUAVgAGUEcQgfgRgSgfQgRggAAgpQgBgpATggQASggAfgRQAggRAnAAQAnAAAfARQAgARASAgQASAgABApQAAApgUAgQgSAfggARQggASgnAAQgnAAgfgSgAGqBoQgTAUgBAnQAAAmAUAVQATAUAdAAQATAAAQgJQAQgJAKgSQAJgSABgZQAAgngVgUQgUgVgdAAQgeAAgTAVgAkiEiQgagMgPgVQgPgUgCgZIBEAAQACAQAOAKQANAKAUAAQAUAAAKgIQALgHAAgNQAAgNgNgGQgOgHgcgHQgfgIgTgHQgTgIgOgQQgOgQAAgbQAAgXANgSQANgTAYgKQAYgLAgAAQAwAAAeAYQAcAYADApIhBAAQgBgQgNgKQgMgJgTAAQgTAAgKAHQgKAGABANQAAANANAHQAOAHAcAHQAdAIATAIQATAHAOARQAOAQAAAaQAAAYgMASQgNATgYAKQgZALgfAAQgiAAgagMgAtfEcQgfgRgSgfQgRggAAgpQAAgpASggQASggAfgRQAggRAnAAQAmAAAgARQAgARASAgQASAgABApQAAApgTAgQgTAfggARQggASgnAAQgnAAgfgSgAtJBoQgTAUAAAnQgBAmAUAVQATAUAdAAQASAAARgJQAQgJAKgSQAKgSAAgZQAAgngVgUQgUgVgdAAQgeAAgTAVgAyOEcQgfgRgSgfQgSggAAgpQABgpARggQATggAggRQAfgRAnAAQAnAAAfARQAgARASAgQATAgAAApQgBApgSAgQgTAfggARQggASgnAAQgnAAgfgSgAx4BoQgUAUABAnQAAAmASAVQAUAUAdAAQATAAAQgJQAQgJAJgSQALgSgBgZQABgngVgUQgUgVgdAAQgdAAgUAVgAUCEhQgMgLAAgRQAAgRAMgLQALgMATAAQASAAALAMQANALAAARQAAARgNALQgLAMgSAAQgTAAgLgMgAnDEpIhbhyIAAByIhEAAIAAlmIBEAAIAADLIBahyIBZAAIh3CHIB4CGgA0/EpIAAlmIBDAAIAAFmgAn+hiQgcgRgQggQgRggABgpQgBgpARggQAQgfAcgRQAcgRAiAAQAfAAAWAMQAWAMAOATIAAgnIBFAAIAAENIhFAAIAAgnQgNATgXAMQgXANgeAAQgiAAgcgSgAnRkhQgQAJgKASQgKARAAAZQAAAYAKASQAKATAQAJQAQAKASAAQAUAAAQgJQARgKAJgSQAKgSAAgYQAAgZgKgSQgJgRgRgKQgQgJgUAAQgSAAgQAJgA0KheQgdgMgQgWQgRgXAAgfIBJAAQABAUAOANQAMAMAYAAQAYAAAOgMQANgLAAgSQAAgQgJgJQgKgKgNgFIgmgNQghgKgVgJQgVgJgOgUQgPgTAAggQAAgeAPgWQAOgXAcgMQAbgMAjAAQA0AAAiAaQAgAZAEAuIhLAAQgBgRgOgMQgOgLgWAAQgVAAgMAKQgMAKABAUQgBANAKAJQAJAJANAGIAmANQAgAJAWAKQAUAKAQATQAPAUgBAfQABAbgOAYQgOAXgcAOQgbAOglAAQgkAAgcgNgAA1hVQhUAAAAhTIAAiCIghAAIAAg4IAhAAIAAhCIBDAAIAABCIA9AAIAAA4Ig9AAIAACCQAAAOAHAGQAGAGAQAAIAgAAIAAA5gAjnhVIAAkNIBEAAIAAAqQANgVAVgNQAWgMAaAAIAABIIgSAAQgfAAgQAPQgRAPAAAlIAACGgAqmhVIAAiUQgBgggQgRQgQgQgcAAQgbAAgRAQQgQARAAAgIAACUIhDAAIAAiUQgBgggQgRQgQgQgcAAQgbAAgRAQQgQARAAAgIAACUIhEAAIAAkNIBEAAIAAAhQANgRAUgKQAWgKAYAAQAfAAAaAOQAYANAOAZQANgXAZgPQAZgOAdAAQAxAAAfAfQAeAeAAA2IAACeg");
	this.shape.setTransform(141.1,61.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(5.8,18.7,270.7,85.89999999999999), null);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE7BGQgMgHgHgMQgGgMAAgRQAAgQAGgMQAHgMAMgHQAMgGAQAAQAQAAAMAGQALAHAHAMQAHALAAAQIgBAJIhJAAQABAKAFAFQAGAFAIAAQAMAAAFgKIAjAAQgDALgHAIQgHAIgKAFQgLAFgNAAQgPAAgNgHgAFrAMQAAgIgGgEQgGgFgIAAQgIAAgGAFQgGADgBAJIApAAIAAAAgAC9BGQgLgHgGgMQgGgNAAgQQAAgQAGgMQAGgMALgHQAKgGANAAQALAAAIAEQAJAEAFAIIAAgxIAhAAIAACLIghAAIAAgPQgFAIgIAEQgIAFgMAAQgNAAgKgHgADNADQgGAHAAAMQAAAMAGAHQAHAHAKAAQAKAAAGgHQAHgHAAgMQAAgMgHgHQgGgGgKAAQgKAAgHAGgAhIBIQgKgFgHgIQgGgIgBgLIAgAAQABAGAFADQAEAEAHAAQAGAAADgDQAEgCAAgEQAAgEgFgDIgQgEQgLgDgIgDQgHgDgGgGQgFgHAAgKQAAgJAFgHQAFgIAKgEQAJgEAOAAQAUAAALAKQAMAJACAQIgeAAQgBgFgEgDQgEgDgHAAQgGAAgDACQgDACAAADQAAAFAFACQAFACAKACIATAGQAIADAFAHQAGAGAAALQAAAKgFAHQgFAHgKAFQgKAEgNAAQgOAAgLgFgAkiBGQgMgHgHgMQgHgMAAgRQAAgQAHgMQAHgMAMgHQAMgGAQAAQAPAAAMAGQAMAHAHAMQAGALAAAQIAAAJIhKAAQABAKAGAFQAFAFAJAAQAMAAAEgKIAjAAQgDALgHAIQgHAIgKAFQgKAFgNAAQgQAAgMgHgAjzAMQAAgIgGgEQgFgFgJAAQgIAAgGAFQgFADgBAJIAoAAIAAAAgAB5BLIAAhpIAhAAIAABpgAAtBLIAAhpIAhAAIAAASQAFgJAJgFQAIgFALAAIAAAiIgJAAQgMAAgGAFQgGAFAAANIAAAxgAibBLQgSAAgJgIQgKgJAAgUIAAgpIgNAAIAAgbIANAAIAAgaIAgAAIAAAaIAVAAIAAAbIgVAAIAAAqQAAAFACACQADACAFAAIAMAAIAAAbgAmLBLIAAiEIAhAAIAABrIAqAAIAAAZgAiAgGIAKgzIAhAAIgVAzgAB7guQgFgFAAgHQAAgIAFgFQAGgFAIAAQAJAAAFAFQAGAFAAAIQAAAHgGAFQgFAFgJAAQgIAAgGgFg");
	this.shape.setTransform(0.575,-0.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// cta_box
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AoICIIAAkPIQRAAIAAEPg");
	this.shape_1.setTransform(0,0.45);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-52.1,-13.1,104.2,27.2), null);


// stage content:
(lib.REV659_Wave2_Awareness_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [145];
	// timeline functions:
	this.frame_145 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(145).call(this.frame_145).wait(1));

	// mask_idn (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AoiBMIAAiXIRFAAIAACXg");
	var mask_graphics_14 = new cjs.Graphics().p("AoRCiIAAlDIQjAAIAAFDg");
	var mask_graphics_24 = new cjs.Graphics().p("AorEPIAAkNIAzAAIAAkQIQkAAIAAFEIi5AAIAADZg");
	var mask_graphics_91 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_92 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_93 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_94 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_95 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_96 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_97 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_98 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_99 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_100 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");
	var mask_graphics_101 = new cjs.Graphics().p("A7Pv9MAgngBJMABKAhEMggnABJgAbQDSIgXAZg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:45.15,y:-9.025}).wait(14).to({graphics:mask_graphics_14,x:47.225,y:7.35}).wait(10).to({graphics:mask_graphics_24,x:28.025,y:21.55}).wait(10).to({graphics:null,x:0,y:0}).wait(57).to({graphics:mask_graphics_91,x:151.2212,y:96.471}).wait(1).to({graphics:mask_graphics_92,x:170.4465,y:96.471}).wait(1).to({graphics:mask_graphics_93,x:189.6714,y:96.471}).wait(1).to({graphics:mask_graphics_94,x:208.8968,y:96.471}).wait(1).to({graphics:mask_graphics_95,x:228.1217,y:96.471}).wait(1).to({graphics:mask_graphics_96,x:247.347,y:96.471}).wait(1).to({graphics:mask_graphics_97,x:266.5719,y:96.471}).wait(1).to({graphics:mask_graphics_98,x:285.7968,y:96.471}).wait(1).to({graphics:mask_graphics_99,x:305.0217,y:96.471}).wait(1).to({graphics:mask_graphics_100,x:324.2466,y:96.471}).wait(1).to({graphics:mask_graphics_101,x:343.4715,y:96.471}).wait(1).to({graphics:null,x:0,y:0}).wait(44));

	// HEAD1
	this.instance = new lib.HEAD1();
	this.instance.setTransform(3.35,-1.6,0.4632,0.4632,0,0,0,0.2,-0.1);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},102).wait(44));

	// mask_idn_copy (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_91 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_92 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_93 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_94 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_95 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_96 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_97 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_98 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_99 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_100 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");
	var mask_1_graphics_101 = new cjs.Graphics().p("A7Ov9MAgmgBJMABKAhEMggnABJgAbPDSIgWAZg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(91).to({graphics:mask_1_graphics_91,x:-59.9796,y:89.8119}).wait(1).to({graphics:mask_1_graphics_92,x:-40.7507,y:89.811}).wait(1).to({graphics:mask_1_graphics_93,x:-21.5231,y:89.811}).wait(1).to({graphics:mask_1_graphics_94,x:-2.2955,y:89.8105}).wait(1).to({graphics:mask_1_graphics_95,x:16.933,y:89.8101}).wait(1).to({graphics:mask_1_graphics_96,x:36.1606,y:89.8101}).wait(1).to({graphics:mask_1_graphics_97,x:55.3882,y:89.8101}).wait(1).to({graphics:mask_1_graphics_98,x:74.6163,y:89.8092}).wait(1).to({graphics:mask_1_graphics_99,x:93.8443,y:89.8092}).wait(1).to({graphics:mask_1_graphics_100,x:113.0719,y:89.8092}).wait(1).to({graphics:mask_1_graphics_101,x:132.2203,y:89.8119}).wait(1).to({graphics:null,x:0,y:0}).wait(44));

	// HEAD2
	this.instance_1 = new lib.HEAD2();
	this.instance_1.setTransform(3.95,2.55,0.5555,0.5555,0,0,0,0.1,0);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(91).to({_off:false},0).wait(55));

	// CTA
	this.instance_2 = new lib.CTA();
	this.instance_2.setTransform(273.4,14.6,0.6064,0.6064,0,0,0,0.2,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(62).to({regX:0.4,regY:0.2,scaleX:0.7276,scaleY:0.7276,x:273.6},3,cjs.Ease.quadInOut).to({regX:0.2,regY:0.1,scaleX:0.6064,scaleY:0.6064,x:273.4},6,cjs.Ease.quadInOut).wait(64).to({regX:0.4,regY:0.2,scaleX:0.7276,scaleY:0.7276,x:273.6},3,cjs.Ease.quadInOut).to({regX:0.2,regY:0.1,scaleX:0.6064,scaleY:0.6064,x:273.4},6,cjs.Ease.quadInOut).wait(2));

	// LOGO
	this.instance_3 = new lib.RevivierLogorevsvg("synched",0);
	this.instance_3.setTransform(274.65,37.45,0.2778,0.2778,0,0,0,142.4,26.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(146));

	// footer_bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Am7G8IAAt3IN3AAIAAN3g");
	this.shape.setTransform(-1.125,191.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(146));

	// mask_idn (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("AEKHhIgFgCIqchTQgHABgFgEIAAAAQgDgCgBgCIAAAAIABgCIgEgTQgJgIgDgEIAAAAQgCgDgEgBIAAAAIgDAAIhagHIgFgBIAAAAQgHgCgCgDIAAAAQgCgDgBgHIAAAAIgBgGIAUpJQABgGADgDIAAAAQABgCAFgCIAAAAIAEgBIAAAAIQhjLIAFgBQAGABAEAGIAAAAQAEAFAAAFIAAAAIABACIAAAAIAAABIAAAAIgGN3IgDAHQgDAIgFAFIAAAAQgGAEgGAAIAAAAIgFgCIjBgVQgQAAgGAEIAAAAQgGAEgHAIIAAAAIgHAUIgDAEIgJAJIAAAAQgDAEgFAAIAAAAIgBAAg");
	var mask_2_graphics_1 = new cjs.Graphics().p("AEHHbIgFgBIqUhTQgIACgEgEIAAAAQgDgCgBgCIAAAAIAAgCIgEgTQgIgHgEgFIAAAAQgCgDgDgBIAAAAIgDAAIhZgHIgGgBIAAAAQgGgCgCgDIAAAAQgCgDgBgHIAAAAIgBgGIATpCQACgGACgDIAAAAQACgCAFgCIAAAAIAEgBIAAAAIQVjJIAFAAQAGAAAEAGIAAAAQAEAFABAFIAAAAIAAACIAAAAIAAABIAAAAIgGNuIgDAGQgDAIgFAFIAAAAQgFAEgHAAIAAAAIgFgCIi/gUQgPAAgGADIAAAAQgGAEgIAIIAAAAIgGAUIgDAEIgJAJIAAAAQgDADgFAAIAAAAIgBAAg");
	var mask_2_graphics_2 = new cjs.Graphics().p("AEEHWIgFgBIqNhSQgHABgFgDIAAAAQgDgCgBgDIAAAAIABgBIgEgTQgIgHgEgFIAAAAQgCgDgDgBIAAAAIgDAAIhYgHIgGgBIAAAAQgGgCgCgDIAAAAQgDgDAAgGIAAAAIgBgGIATo9QABgFADgDIAAAAQACgCAEgCIAAAAIAEgBIAAAAIQLjHIAFAAQAFABAEAFIAAAAQAEAFABAEIAAAAIAAADIAAAAIAAABIAAAAIgGNkIgCAHQgEAIgFAEIAAAAQgFAFgGgBIAAAAIgGgCIi8gUQgQAAgGAEIAAAAQgFADgIAJIAAAAIgGATIgDAEIgIAJIAAAAQgEADgFAAIAAAAIgBAAg");
	var mask_2_graphics_3 = new cjs.Graphics().p("AEBHRIgEgBIqHhRQgHABgFgDIAAAAQgDgCAAgDIAAAAIAAgBIgEgTQgIgHgDgFIAAAAQgCgDgEAAIAAAAIgDAAIhXgHIgFgBIAAAAQgGgCgDgDIAAAAQgCgDgBgHIAAAAIAAgFIATo3QABgFACgEIAAAAQACgCAFgBIAAAAIAEgBIAAAAIP/jFIAFAAQAGABADAFIAAAAQAEAFABAEIAAAAIAAACIAAAAIAAACIAAAAIgGNbIgCAGQgDAIgFAEIAAAAQgGAFgGgBIAAAAIgFgBIi7gUQgPAAgGADIAAAAQgGAEgHAIIAAAAIgGATIgDAEIgIAJIAAAAQgEADgFAAIAAAAIgBAAg");
	var mask_2_graphics_4 = new cjs.Graphics().p("AD/HMIgFgBIqAhQQgHABgEgDIAAAAQgDgCgBgDIAAAAIAAgBIgDgTQgIgHgEgEIAAAAQgCgDgDgBIAAAAIgDAAIhWgHIgGgBIAAAAQgGgCgCgDIAAAAQgCgDgBgGIAAAAIAAgGIASowQABgFADgEIAAAAQACgCAEgBIAAAAIAEgBIAAAAIP1jDIAFAAQAFAAAEAGIAAAAQADAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgGNSIgCAHQgDAHgFAFIAAAAQgFAEgGAAIAAAAIgFgCIi5gUQgPAAgGAEIAAAAQgGADgHAJIAAAAIgGASIgDAEIgIAJIAAAAQgDADgGAAIAAAAIAAAAg");
	var mask_2_graphics_5 = new cjs.Graphics().p("AD8HIIgFgCIp5hPQgGABgFgDIAAAAQgDgCgBgCIAAAAIABgCIgEgSQgIgHgDgFIAAAAQgCgDgEAAIAAAAIgCAAIhWgHIgFgBIAAAAQgGgCgCgDIAAAAQgDgDAAgGIAAAAIgBgGIATorQABgFACgDIAAAAQACgCAEgBIAAAAIAEgBIAAAAIPqjBIAFgBQAGABADAFIAAAAQAEAFABAFIAAAAIAAACIAAAAIAAABIAAAAIgGNJIgCAHQgDAHgFAEIAAAAQgFAFgGgBIAAAAIgGgBIi2gUQgPAAgGAEIAAAAQgGADgHAIIAAAAIgFATIgEAEIgIAIIAAAAQgDAEgFAAIAAAAIgBAAg");
	var mask_2_graphics_6 = new cjs.Graphics().p("AD5HDIgEgBIpyhPQgHABgFgDIAAAAQgDgCAAgCIAAAAIAAgCIgEgSQgIgHgDgEIAAAAQgCgDgDgBIAAAAIgDAAIhUgHIgGgBIAAAAQgGgCgCgCIAAAAQgCgDgBgHIAAAAIAAgFIASolQABgFADgDIAAAAQABgCAFgCIAAAAIAEAAIAAAAIPfjAIAFAAQAFABAEAFIAAAAQADAFABAEIAAAAIAAACIAAAAIAAACIAAAAIgGNAIgCAGQgDAIgFAEIAAAAQgFAEgGAAIAAAAIgFgCIi1gTQgOAAgGADIAAAAQgGAEgHAIIAAAAIgFASIgEAEIgIAIIAAAAQgDAEgFAAIAAAAIgBAAg");
	var mask_2_graphics_7 = new cjs.Graphics().p("AD3G+IgFgBIprhOQgHABgFgDIAAAAQgDgCAAgCIAAAAIAAgCIgEgSQgHgGgEgFIAAAAQgCgDgDAAIAAAAIgDAAIhTgHIgFgBIAAAAQgGgCgCgDIAAAAQgDgDAAgGIAAAAIgBgFIASofQABgFADgEIAAAAQABgCAFgBIAAAAIAEgBIAAAAIPVi9IAEAAQAGABADAFIAAAAQAEAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgGM4IgCAGQgDAHgFAFIAAAAQgFAEgGgBIAAAAIgFgBIizgTQgPAAgFADIAAAAQgGADgGAIIAAAAIgGASIgEAEIgHAJIAAAAQgEADgFAAIAAAAIAAAAg");
	var mask_2_graphics_8 = new cjs.Graphics().p("AD0G5IgEgBIpmhNQgGACgFgEIAAAAQgDgCAAgCIAAAAIAAgBIgDgSQgIgHgEgEIAAAAQgBgDgEgBIAAAAIgCAAIhTgGIgFgBIAAAAQgGgCgCgDIAAAAQgCgDgBgGIAAAAIgBgFIASoaQABgFADgDIAAAAQACgCAEgBIAAAAIAEgBIAAAAIPLi7IAEAAQAFAAAEAFIAAAAQADAFABAEIAAAAIABACIAAAAIgBACIAAAAIgFMuIgCAHQgDAHgFAEIAAAAQgFAEgGAAIAAAAIgFgCIixgSQgPAAgFADIAAAAQgGADgGAIIAAAAIgGASIgDAEIgIAIIAAAAQgDADgFAAIAAAAIgBAAg");
	var mask_2_graphics_9 = new cjs.Graphics().p("ADyG1IgFgBIpfhMQgGABgFgEIAAAAQgDgCAAgCIAAAAIAAgBIgDgSQgIgGgDgFIAAAAQgCgCgDgBIAAAAIgDAAIhSgHIgFgBIAAAAQgGgBgCgDIAAAAQgCgDgBgGIAAAAIAAgGIARoTQACgFACgDIAAAAQACgCAEgCIAAAAIAEAAIAAAAIPAi6IAFAAQAFABAEAFIAAAAQADAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgFMmIgCAHQgDAHgFAEIAAAAQgFAEgGAAIAAAAIgFgCIivgTQgPAAgFAEIAAAAQgFADgHAIIAAAAIgGARIgDAFIgIAIIAAAAQgDADgFAAIAAAAIAAAAg");
	var mask_2_graphics_10 = new cjs.Graphics().p("ADvGwIgEgBIpZhLQgGABgFgDIAAAAQgDgCAAgCIAAAAIAAgCIgDgRQgIgHgDgEIAAAAQgCgDgDAAIAAAAIgDAAIhRgHIgFgBIAAAAQgGgCgCgCIAAAAQgCgDgBgGIAAAAIAAgGIARoOQACgFACgDIAAAAQACgCAEgBIAAAAIAEgBIAAAAIO2i3IAFAAQAFAAAEAFIAAAAQADAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgGMeIgCAHQgDAHgEAEIAAAAQgFAEgGgBIAAAAIgFgBIitgTQgOAAgGAEIAAAAQgFADgHAIIAAAAIgFARIgEAEIgHAIIAAAAQgDADgFAAIAAAAIgBAAg");
	var mask_2_graphics_11 = new cjs.Graphics().p("ADtGsIgFgBIpShLQgHABgEgDIAAAAQgDgCAAgCIAAAAIAAgBIgDgSQgIgGgDgEIAAAAQgCgDgDgBIAAAAIgDAAIhQgGIgFgBIAAAAQgGgCgCgCIAAAAQgCgDgBgGIAAAAIAAgGIARoIQABgFADgDIAAAAQABgCAEgCIAAAAIAEAAIAAAAIOui2IAEAAQAFABAEAFIAAAAQADAEABAEIAAAAIAAACIAAAAIAAABIAAAAIgGMWIgCAHQgDAHgEAEIAAAAQgFAEgGgBIAAAAIgEgBIisgSQgOAAgGADIAAAAQgFADgHAIIAAAAIgFARIgDAEIgIAIIAAAAQgDADgFAAIAAAAIAAAAg");
	var mask_2_graphics_12 = new cjs.Graphics().p("ADqGoIgEgBIpMhKQgHABgEgDIAAAAQgDgCAAgCIAAAAIAAgCIgEgRQgHgGgDgFIAAAAQgCgCgDgBIAAAAIgDAAIhPgGIgFgBIAAAAQgGgCgCgDIAAAAQgCgCgBgGIAAAAIAAgFIARoEQABgFADgDIAAAAQABgCAEgBIAAAAIAEgBIAAAAIOkizIAEgBQAFABAEAFIAAAAQADAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgGMOIgCAGQgCAHgFAEIAAAAQgFAEgFgBIAAAAIgFgBIiqgSQgOAAgFADIAAAAQgGADgGAIIAAAAIgGARIgDAEIgHAHIAAAAQgDAEgFAAIAAAAIgBAAg");
	var mask_2_graphics_13 = new cjs.Graphics().p("ADoGjIgEgBIpHhJQgGABgEgDIAAAAQgDgCgBgCIAAAAIAAgBIgDgRQgHgGgDgFIAAAAQgCgCgDgBIAAAAIgDAAIhOgGIgFgBIAAAAQgGgCgCgDIAAAAQgCgCgBgGIAAAAIAAgFIARn/QABgEACgDIAAAAQACgCAEgCIAAAAIAEAAIAAAAIOaiyIAEAAQAFAAAEAFIAAAAQADAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgFMGIgCAGQgDAHgFAEIAAAAQgFAEgFgBIAAAAIgFgBIiogSQgOAAgFADIAAAAQgFADgHAIIAAAAIgFARIgDADIgIAIIAAAAQgDADgEAAIAAAAIgBAAg");
	var mask_2_graphics_14 = new cjs.Graphics().p("ADmGfIgFgBIpAhIQgHABgEgDIAAAAQAAgBgBAAQgBgBAAAAQAAgBgBAAQAAgBAAAAIAAAAIAAgCIgDgQQgHgHgDgEIAAAAQgCgCgDgBIAAAAIgDAAIhNgGIgGgBIAAAAQgFgCgCgCIAAAAQgCgDgBgGIAAAAIAAgFIARn5QABgFACgDIAAAAQACgCAEgBIAAAAIADgBIAAAAIORiwIAFAAQAFABADAEIAAAAQADAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgFL+IgCAGQgDAHgFAEIAAAAQgEAEgGgBIAAAAIgEgBIingSQgOAAgFADIAAAAQgFADgGAIIAAAAIgGARIgDADIgHAIIAAAAQgDADgFAAIAAAAIAAAAg");
	var mask_2_graphics_15 = new cjs.Graphics().p("ADjGbIgEgBIo7hIQgGACgEgEIAAAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAAAIAAAAIAAgCIgDgQQgIgHgDgEIAAAAQgCgCgDgBIAAAAIgCAAIhNgGIgFgBIAAAAQgFgCgCgCIAAAAQgCgDgBgGIAAAAIAAgFIAQn0QABgFADgDIAAAAQABgCAEgBIAAAAIAEgBIAAAAIOIiuIAEAAQAFABADAEIAAAAQADAFABAEIAAAAIAAACIAAAAIAAABIAAAAIgFL2IgCAGQgDAHgEAEIAAAAQgFAEgFgBIAAAAIgFgBIilgSQgNAAgFAEIAAAAQgGADgGAHIAAAAIgFARIgDADIgHAIIAAAAQgDADgFAAIAAAAIgBAAg");
	var mask_2_graphics_16 = new cjs.Graphics().p("ADhGXIgEgBIo1hHQgGABgFgDIAAAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAAAIAAgBIgDgRQgHgGgDgEIAAAAQgCgCgDgBIAAAAIgCAAIhMgGIgFgBIAAAAQgGgCgCgCIAAAAQgCgDAAgGIAAAAIgBgFIARnvQABgFACgCIAAAAQACgCADgBIAAAAIAEgBIAAAAIN/itIAEAAQAFABAEAEIAAAAQADAFAAAEIAAAAIABACIAAAAIAAABIAAAAIgGLvIgCAGQgCAGgFAEIAAAAQgEAEgGAAIAAAAIgEgCIikgRQgNAAgFADIAAAAQgFADgGAHIAAAAIgGARIgDADIgHAIIAAAAQgDADgEAAIAAAAIgBAAg");
	var mask_2_graphics_17 = new cjs.Graphics().p("ADfGTIgEgBIowhGQgGABgEgDIAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBIAAAAIAAgBIgDgRQgHgGgDgEIAAAAQgCgCgDgBIAAAAIgDAAIhLgGIgFgBIAAAAQgFgBgCgDIAAAAQgCgDgBgFIAAAAIAAgFIAQnrQABgEACgDIAAAAQACgCAEgBIAAAAIADgBIAAAAIN3irIAEAAQAFABADAEIAAAAQADAFABAEIAAAAIAAABIAAAAIAAABIAAAAIgFLoIgCAGQgDAHgEAEIAAAAQgFADgFAAIAAAAIgFgBIihgSQgOAAgFADIAAAAQgFADgGAIIAAAAIgFAQIgDAEIgHAHIAAAAQgDADgEAAIAAAAIgBAAg");
	var mask_2_graphics_18 = new cjs.Graphics().p("ADdGPIgEgBIorhFQgGABgEgDIAAAAIgDgEIAAAAIAAgBIgDgRQgHgGgDgEIAAAAQgCgCgCgBIAAAAIgDAAIhLgGIgEgBIAAAAQgGgBgCgDIAAAAQgBgCgBgGIAAAAIgBgFIARnmQABgEACgDIAAAAQABgCAEgBIAAAAIAEgBIAAAAINtipIAFAAQAEABADAEIAAAAQAEAEAAAEIAAAAIABACIAAAAIgBABIAAAAIgFLhIgBAGQgDAGgFAEIAAAAQgEAEgFgBIAAAAIgFgBIiggRQgNAAgFADIAAAAQgFADgGAHIAAAAIgFAQIgDAEIgHAHIAAAAQgDADgFAAIAAAAIAAAAg");
	var mask_2_graphics_19 = new cjs.Graphics().p("ADbGLIgEgBIolhFQgGABgEgDIAAAAIgDgDIAAAAIAAgCIgDgQIgKgJIAAAAQgCgDgDgBIAAAAIgCAAIhKgFIgFgBIAAAAQgFgCgCgCIAAAAQgCgDgBgGIAAAAIAAgEIAQniQABgEACgDIAAAAQACgCADgBIAAAAIAEAAIAAAAINlioIAEAAQAFAAADAFIAAAAQADAEABAEIAAAAIAAACIAAAAIAAABIAAAAIgFLZIgCAGQgDAHgEADIAAAAQgEAEgGAAIAAAAIgEgCIifgRQgNAAgFADIAAAAQgEADgHAHIAAAAIgFAQIgDAEIgGAHIAAAAQgDADgFAAIAAAAIAAAAg");
	var mask_2_graphics_20 = new cjs.Graphics().p("ADZGIIgFgBIofhFQgGABgEgDIAAAAIgDgDIAAAAIAAgCIgDgPIgKgKIAAAAQgCgDgCAAIAAAAIgDAAIhJgGIgFgBIAAAAQgFgCgCgCIAAAAQgCgDAAgFIAAAAIgBgFIAQncQABgFACgDIAAAAQACgBADgCIAAAAIAEAAIAAAAINdimIAEgBQAFABADAFIAAAAQADAEABAEIAAAAIAAABIAAAAIAAABIAAAAIgFLTIgCAGQgDAGgEAEIAAAAQgFAEgFgBIAAAAIgEgBIidgRQgNAAgFADIAAAAQgFADgGAHIAAAAIgFAQIgDADIgHAIIAAAAQgCADgFAAIAAAAIAAAAg");
	var mask_2_graphics_21 = new cjs.Graphics().p("ADXGEIgFgBIoahEQgGABgEgDIAAAAIgDgDIAAAAIAAgCIgDgPIgKgKIAAAAQgBgCgDgBIAAAAIgCAAIhJgGIgFgBIAAAAQgFgBgCgDIAAAAQgBgCgBgGIAAAAIgBgEIAQnYQABgFACgDIAAAAQACgBADgBIAAAAIAEgBIAAAAINVilIAEAAQAEABAEAEIAAAAQADAEAAAEIAAAAIABACIAAAAIgBABIAAAAIgELMIgCAFQgDAHgEADIAAAAQgFAEgFAAIAAAAIgEgCIicgQQgMAAgFADIAAAAQgFADgGAHIAAAAIgFAPIgDAEIgHAHIAAAAQgDADgEAAIAAAAIAAAAg");
	var mask_2_graphics_22 = new cjs.Graphics().p("ADVGAIgEgBIoWhDQgGABgEgDIAAAAIgDgDIAAAAIAAgBIgDgQIgJgKIAAAAQgCgCgDgBIAAAAIgCAAIhIgFIgFgBIAAAAQgFgCgBgCIAAAAQgCgDgBgFIAAAAIAAgFIAPnTQABgFACgDIAAAAQACgBADgBIAAAAIAEgBIAAAAINNijIAEAAQAEAAADAFIAAAAQADAEABAEIAAAAIAAABIAAAAIAAABIAAAAIgFLGIgBAFQgDAGgEAEIAAAAQgFAEgFgBIAAAAIgEgBIiagQQgNAAgFACIAAAAQgEADgGAHIAAAAIgFAQIgDADIgHAHIAAAAQgDADgEAAIAAAAIAAAAg");
	var mask_2_graphics_23 = new cjs.Graphics().p("ADTF9IgEgBIoRhDQgGABgEgCIAAAAIgDgEIAAAAIAAgBIgCgQIgKgJIAAAAQgCgDgCAAIAAAAIgDAAIhHgGIgFgBIAAAAQgFgBgBgDIAAAAQgCgCgBgGIAAAAIAAgEIAPnQQABgEACgDIAAAAQACgBADgBIAAAAIAEgBIAAAAINFiiIAEAAQAEABADAEIAAAAQADAEABAEIAAAAIAAACIAAAAIAAABIAAAAIgFK+IgBAGQgDAGgEAEIAAAAQgFADgFAAIAAAAIgEgBIiZgRQgMAAgFADIAAAAQgFADgFAHIAAAAIgFAPIgDAEIgHAHIAAAAQgDADgEAAIAAAAIAAAAg");
	var mask_2_graphics_24 = new cjs.Graphics().p("ADRF5IgEgBIoMhBQgGABgEgDIAAAAIgDgEIAAAAIABgBIgDgPIgKgKIAAAAQgCgCgCgBIAAAAIgDAAIhGgFIgFgBIAAAAQgFgCgBgCIAAAAQgCgDgBgFIAAAAIAAgFIAPnLQABgEACgDIAAAAQABgBAEgBIAAAAIADgBIAAAAIM+igIAEAAQAEAAADAFIAAAAQADAEABADIAAAAIAAACIAAAAIAAABIAAAAIgFK4IgBAGQgDAGgEAEIAAAAQgEADgFAAIAAAAIgFgCIiXgQQgMAAgFADIAAAAQgFADgGAHIAAAAIgEAPIgDADIgHAHIAAAAQgDADgEAAIAAAAIAAAAg");
	var mask_2_graphics_25 = new cjs.Graphics().p("ADPF2IgEgBIoHhBQgGABgEgDIAAAAIgDgEIAAAAIABgBIgDgPIgKgJIAAAAQgBgDgDAAIAAAAIgCAAIhGgGIgFgBIAAAAQgFgBgCgDIAAAAQgBgCgBgFIAAAAIAAgFIAPnHQABgEACgDIAAAAQABgBAEgBIAAAAIADgBIAAAAIM2ifIAEAAQAFABACAEIAAAAQADAEABAEIAAAAIAAABIAAAAIAAABIAAAAIgEKyIgCAGQgDAGgEADIAAAAQgEAEgFgBIAAAAIgEgBIiWgQQgNAAgEADIAAAAQgFADgGAHIAAAAIgEAPIgDADIgHAHIAAAAQgCADgFAAIAAAAIAAAAg");
	var mask_2_graphics_26 = new cjs.Graphics().p("ADNFzIgEgBIoChBQgGABgEgDIAAAAIgDgDIAAAAIAAgCIgCgPIgKgJIAAAAQgBgCgDgBIAAAAIgCAAIhGgFIgEgBIAAAAQgFgCgCgCIAAAAQgBgCgBgFIAAAAIgBgFIAPnDQABgEACgDIAAAAQACgBADgCIAAAAIAEAAIAAAAIMuidIAEgBQAFABADAEIAAAAQADAEAAAEIAAAAIABACIAAAAIgBABIAAAAIgEKrIgCAGQgDAGgEADIAAAAQgEAEgFgBIAAAAIgEgBIiUgQQgNAAgEADIAAAAQgFADgGAGIAAAAIgEAPIgDAEIgHAHIAAAAQgCADgEAAIAAAAIgBAAg");
	var mask_2_graphics_27 = new cjs.Graphics().p("ADLFvIgEgBIn+hAQgFABgEgCIAAAAIgDgEIAAAAIAAgBIgCgPIgKgJIAAAAQgBgDgDAAIAAAAIgCAAIhFgGIgEAAIAAAAQgFgCgCgCIAAAAQgCgDAAgFIAAAAIgBgEIAPm/QABgEACgDIAAAAQABgCAEgBIAAAAIADAAIAAAAIMoicIAEAAQAEAAADAEIAAAAQADAFABADIAAAAIAAACIAAAAIAAABIAAAAIgFKlIgCAGQgCAGgEADIAAAAQgEAEgFgBIAAAAIgEgBIiUgQQgMAAgEADIAAAAQgFADgGAGIAAAAIgEAPIgDAEIgHAHIAAAAQgCACgEAAIAAAAIgBAAg");
	var mask_2_graphics_28 = new cjs.Graphics().p("ADJFsIgDgBIn6g/QgFABgEgDIAAAAIgDgDIAAAAIAAgCIgDgOIgJgKIAAAAQgBgCgDAAIAAAAIgCAAIhEgGIgFgBIAAAAQgFgBgBgCIAAAAQgCgDgBgFIAAAAIAAgEIAPm7QABgFACgCIAAAAQABgCADgBIAAAAIAEgBIAAAAIMgiaIAEAAQAEABADAEIAAAAQADAEABADIAAAAIAAACIAAAAIAAABIAAAAIgFKgIgBAFQgDAGgEADIAAAAQgEAEgFgBIAAAAIgEgBIiSgPQgMAAgEACIAAAAQgFADgGAHIAAAAIgEAOIgDAEIgGAGIAAAAQgDADgEAAIAAAAIgBAAg");
	var mask_2_graphics_29 = new cjs.Graphics().p("ADIFpIgEgBIn1g/QgGABgDgDIAAAAIgDgDIAAAAIAAgBIgDgPIgJgJIAAAAQgCgCgCgBIAAAAIgCAAIhEgFIgEgBIAAAAQgFgBgCgDIAAAAQgBgCgBgFIAAAAIgBgEIAPm4QABgEACgCIAAAAQABgCAEgBIAAAAIADgBIAAAAIMaiZIAEAAQAEABADAEIAAAAQADAEAAADIAAAAIABACIAAAAIgBABIAAAAIgEKaIgCAFQgCAGgEAEIAAAAQgEADgFgBIAAAAIgEgBIiRgPQgMAAgEADIAAAAQgFACgFAHIAAAAIgFAOIgDAEIgGAGIAAAAQgDADgEAAIAAAAIAAAAg");
	var mask_2_graphics_30 = new cjs.Graphics().p("ADGFmIgEgBInxg+QgFABgEgDIAAAAIgDgDIAAAAIABgCIgDgOIgJgJIAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIAAAAIgDAAIhDgFIgEgBIAAAAQgFgCgBgCIAAAAQgCgCgBgFIAAAAIAAgFIAOmzQABgEACgDIAAAAQACgBADgBIAAAAIADgBIAAAAIMTiYIAEAAQAEABADAEIAAAAQADAEABADIAAAAIAAACIAAAAIAAABIAAAAIgFKUIgBAFQgDAGgEAEIAAAAQgEADgEAAIAAAAIgEgCIiQgPQgMAAgEADIAAAAQgFACgFAHIAAAAIgFAOIgDAEIgGAGIAAAAQgCADgEAAIAAAAIgBAAg");
	var mask_2_graphics_31 = new cjs.Graphics().p("ADEFjIgDgBIntg+QgGABgDgCIAAAAIgDgEIAAAAIAAgBIgDgOIgJgJIAAAAQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAgBAAIAAAAIgCAAIhCgFIgFgBIAAAAQgEgCgCgCIAAAAQgCgCAAgFIAAAAIgBgFIAPmvQABgEACgDIAAAAQABgCADgBIAAAAIAEAAIAAAAIMMiXIAEAAQAEABADAEIAAAAQADAEAAADIAAAAIABACIAAAAIgBAAIAAAAIgEKQIgCAFQgCAGgEADIAAAAQgEADgFAAIAAAAIgEgBIiOgPQgMAAgEACIAAAAQgFADgFAGIAAAAIgFAPIgCADIgHAGIAAAAQgCADgEAAIAAAAIgBAAg");
	var mask_2_graphics_32 = new cjs.Graphics().p("ADDFgIgEgBInpg9QgFABgEgDIAAAAIgCgDIAAAAIAAgBIgDgPIgJgIIAAAAQAAgBgBAAQAAgBgBAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIhCgFIgEgBIAAAAQgFgCgCgCIAAAAQgBgCgBgFIAAAAIAAgEIAOmtQABgEACgCIAAAAQABgCAEgBIAAAAIADgBIAAAAIMGiVIAEAAQAEABADADIAAAAQACAEABAEIAAAAIAAABIAAAAIAAABIAAAAIgEKKIgCAFQgCAGgEADIAAAAQgEAEgFgBIAAAAIgEgBIiNgPQgMAAgEADIAAAAQgEACgGAGIAAAAIgEAPIgDADIgGAHIAAAAQgDACgEAAIAAAAIAAAAg");
	var mask_2_graphics_33 = new cjs.Graphics().p("ADBFdIgDgBInlg8QgGABgDgDIAAAAIgDgDIAAAAIAAgCIgDgOIgIgIIAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAIAAAAIgDAAIhBgFIgEgBIAAAAQgFgCgBgCIAAAAQgCgCgBgFIAAAAIAAgEIAOmpQABgEACgDIAAAAIAFgCIAAAAIADgBIAAAAIMAiUIADAAQAFAAACAEIAAAAQADAEABADIAAAAIAAACIAAAAIAAABIAAAAIgFKFIgBAFQgDAFgDAEIAAAAQgEADgFAAIAAAAIgEgCIiMgPQgMAAgEADIAAAAQgEADgGAGIAAAAIgEAOIgDADIgGAHIAAAAQgCACgEAAIAAAAIgBAAg");
	var mask_2_graphics_34 = new cjs.Graphics().p("ADAFbIgEgBInhg9QgFABgEgCIAAAAIgDgEIAAAAIABgBIgDgOIgJgJIAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIhBgFIgEgBIAAAAQgFgCgBgCIAAAAQgCgCgBgFIAAAAIAAgEIAOmmQABgEACgCIAAAAIAFgDIAAAAIADAAIAAAAIL6iTIADgBQAFABACAEIAAAAQADAEABADIAAAAIAAACIAAAAIAAABIAAAAIgFJ/IgBAFQgDAGgEADIAAAAQgDADgFAAIAAAAIgEgBIiLgPQgLAAgFADIAAAAQgEACgFAGIAAAAIgFAOIgCAEIgGAGIAAAAQgDADgEAAIAAAAIAAAAg");
	var mask_2_graphics_35 = new cjs.Graphics().p("AC+FYIgDgBIneg8QgFABgEgDIAAAAIgCgDIAAAAIAAgBIgDgOIgIgIIAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAIAAAAIgCAAIhBgFIgEgBIAAAAQgFgBgBgDIAAAAQgCgCAAgFIAAAAIgBgEIAOmiIADgHIAAAAIAEgCIAAAAIAEgBIAAAAIL0iSIADAAQAEABADAEIAAAAQADADABAEIAAAAIAAABIAAAAIAAABIAAAAIgFJ7IgBAFQgDAFgEAEIAAAAQgDADgFgBIAAAAIgEgBIiKgOQgLAAgEACIAAAAQgFADgFAGIAAAAIgEAOIgDADIgGAGIAAAAQgCADgEAAIAAAAIgBAAg");
	var mask_2_graphics_36 = new cjs.Graphics().p("AC9FVIgEAAInag8QgFABgDgDIAAAAIgDgDIAAAAIAAgBIgCgOIgJgIIAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIAAAAIgCAAIhAgFIgEgBIAAAAQgFgBgBgDIAAAAQgCgCAAgEIAAAAIgBgFIAOmfQABgEACgCIAAAAIAEgDIAAAAIADAAIAAAAILviRIADAAQAFAAACAEIAAAAQADAEABADIAAAAIAAACIAAAAIAAABIAAAAIgFJ1IgBAFQgDAGgDADIAAAAQgEADgFAAIAAAAIgEgBIiIgPQgMAAgEADIAAAAQgEACgFAHIAAAAIgFANIgDADIgFAHIAAAAQgDACgEAAIAAAAIAAAAg");
	var mask_2_graphics_37 = new cjs.Graphics().p("AC7FTIgDgBInWg7QgGABgDgDIAAAAIgDgDIAAAAIAAgBIgCgOIgJgIIAAAAQAAgBgBAAQAAgBAAAAQgBAAgBgBQAAAAgBAAIAAAAIgCAAIg/gFIgEgBIAAAAQgFgBgBgCIAAAAQgCgCgBgFIAAAAIAAgEIAOmdIADgGIAAAAIAEgCIAAAAIADgBIAAAAILpiQIAEAAQAEABACAEIAAAAQADADABAEIAAAAIAAABIAAAAIAAABIAAAAIgFJxIgBAFQgCAGgEADIAAAAQgEADgEAAIAAAAIgEgBIiIgPQgLAAgFADIAAAAQgEACgFAGIAAAAIgEAOIgDADIgGAGIAAAAQgCADgEAAIAAAAIgBAAg");
	var mask_2_graphics_38 = new cjs.Graphics().p("AC6FQIgDAAInTg7QgFABgEgDIAAAAIgDgDIAAAAIABgBIgDgOIgIgIIAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIAAAAIgCAAIg/gFIgEgBIAAAAQgFgBgBgCIAAAAQgCgCgBgFIAAAAIAAgEIAOmZIACgGIAAAAIAFgDIAAAAIADgBIAAAAILjiOIAEAAQAEAAADAEIAAAAQACAEABADIAAAAIAAABIAAAAIAAABIAAAAIgEJtIgCAFQgCAFgEAEIAAAAQgEADgEgBIAAAAIgEgBIiHgOQgLAAgEACIAAAAQgEADgGAGIAAAAIgEAOIgCADIgGAGIAAAAQgDACgDAAIAAAAIgBAAg");
	var mask_2_graphics_39 = new cjs.Graphics().p("AC5FOIgEgBInPg6QgFABgEgDIAAAAIgCgDIAAAAIAAgBIgDgNIgIgJIAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQgBAAAAAAIAAAAIgCAAIg/gFIgEgBIAAAAQgEgCgCgCIAAAAQgBgCgBgEIAAAAIAAgFIANmWIADgGIAAAAIAEgDIAAAAIADAAIAAAAILfiOIADAAQAEABADADIAAAAQADAEAAADIAAAAIAAACIAAAAIAAABIAAAAIgEJoIgCAFQgCAFgEADIAAAAQgDAEgFgBIAAAAIgDgBIiGgOQgMAAgEACIAAAAQgEADgFAGIAAAAIgEANIgDADIgGAHIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_40 = new cjs.Graphics().p("AC4FMIgEgBInMg6QgFABgEgDIAAAAIgCgDIAAAAIAAgBIgDgNIgIgJIAAAAQgBAAAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIg+gFIgEgBIAAAAQgFgBgBgCIAAAAQgCgCAAgFIAAAAIgBgEIAOmUIACgGIAAAAIAFgCIAAAAIADgBIAAAAILZiNIAEAAQAEABACAEIAAAAQADADAAADIAAAAIABACIAAAAIAAABIAAAAIgFJkIgBAFQgDAFgDADIAAAAQgEADgEAAIAAAAIgEgBIiFgOQgLAAgEACIAAAAQgEADgFAGIAAAAIgFANIgCADIgGAGIAAAAQgCADgEAAIAAAAIAAAAg");
	var mask_2_graphics_41 = new cjs.Graphics().p("AC2FJIgDAAInKg6QgFABgDgCIAAAAIgCgDIAAAAIAAgCIgDgNIgIgIIAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIAAAAIgCAAIg+gFIgEAAIAAAAQgEgCgCgCIAAAAQgBgCgBgFIAAAAIAAgEIANmQIADgHIAAAAIAEgCIAAAAIADgBIAAAAILViLIADAAQAEAAADAEIAAAAQACADABAEIAAAAIAAABIAAAAIAAABIAAAAIgEJgIgCAFQgCAFgEADIAAAAQgDADgFAAIAAAAIgDgBIiFgOQgKAAgFACIAAAAQgEADgFAGIAAAAIgEANIgDADIgFAGIAAAAQgDACgDAAIAAAAIgBAAg");
	var mask_2_graphics_42 = new cjs.Graphics().p("AC1FHIgDAAInHg6QgFABgDgCIAAAAIgDgDIAAAAIABgBIgDgOIgIgIIAAAAQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIg9gFIgEgBIAAAAQgFgBgBgCIAAAAQgCgCAAgFIAAAAIgBgEIAOmOIACgGIAAAAIAFgDIAAAAIADAAIAAAAILPiLIAEAAQAEAAACAEIAAAAQADAEAAADIAAAAIABABIAAAAIgBABIAAAAIgEJcIgBAFQgCAFgEADIAAAAQgEADgEAAIAAAAIgEgBIiDgOQgLAAgEACIAAAAQgEADgFAGIAAAAIgEANIgDADIgFAGIAAAAQgDACgDAAIAAAAIgBAAg");
	var mask_2_graphics_43 = new cjs.Graphics().p("AC0FFIgDgBInEg4QgFABgDgDIAAAAIgDgDIAAAAIAAgBIgCgNIgIgIIAAAAQgBgBAAAAQgBgBAAAAQAAAAgBAAQgBgBAAAAIAAAAIgCAAIg9gFIgEAAIAAAAQgEgCgCgCIAAAAQgBgCgBgEIAAAAIAAgFIANmLIADgGIAAAAIAEgDIAAAAIADAAIAAAAILLiKIADAAQAEAAADAEIAAAAQACAEABADIAAAAIAAABIAAAAIAAABIAAAAIgEJYIgCAFQgCAFgDADIAAAAQgEADgEAAIAAAAIgEgBIiCgOQgLAAgEACIAAAAQgEADgFAGIAAAAIgEANIgDADIgGAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_44 = new cjs.Graphics().p("ACzFDIgEgBInAg4QgFABgDgCIAAAAIgDgDIAAAAIAAgCIgCgNIgIgIIAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAIAAAAIgCAAIg9gFIgEgBIAAAAQgEgBgBgCIAAAAQgCgCgBgFIAAAAIAAgEIANmJIADgGIAAAAIAEgCIAAAAIADgBIAAAAILHiJIADAAQAEAAADAEIAAAAQACAEABADIAAAAIAAABIAAAAIAAABIAAAAIgEJUIgCAFQgCAFgEADIAAAAQgDADgFAAIAAAAIgDgBIiCgOQgLAAgEADIAAAAQgEACgFAGIAAAAIgEANIgCADIgGAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_45 = new cjs.Graphics().p("ACyFBIgEAAIm+g4QgEAAgEgCIAAAAIgCgDIAAAAIAAgBIgDgNIgIgIIAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIAAAAIgCAAIg8gFIgEAAIAAAAQgFgCgBgCIAAAAQgCgCAAgEIAAAAIgBgEIANmHIADgGIAAAAIAEgCIAAAAIADgBIAAAAILDiIIADAAQAEAAACAEIAAAAQADADAAADIAAAAIABACIAAAAIAAABIAAAAIgFJRIgBAEQgCAGgEADIAAAAQgDADgFgBIAAAAIgDgBIiBgOQgLAAgEADIAAAAQgEACgFAGIAAAAIgEANIgCADIgGAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_46 = new cjs.Graphics().p("ACxE/IgEAAIm7g4QgFABgDgDIAAAAIgDgDIAAAAIAAgBIgCgNIgIgIIAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIg7gFIgEgBIAAAAQgFgBgBgCIAAAAQgCgCAAgEIAAAAIAAgEIAMmFIADgGIAAAAIAEgCIAAAAIADgBIAAAAIK+iHIAEAAQAEAAACAEIAAAAQADADAAADIAAAAIAAACIAAAAIAAABIAAAAIgEJNIgBAFQgCAFgEADIAAAAQgDADgFAAIAAAAIgDgCIiAgNQgLAAgEACIAAAAQgEADgFAFIAAAAIgEANIgCADIgGAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_47 = new cjs.Graphics().p("ACwE+IgEgBIm5g3QgEAAgEgCIAAAAIgCgDIAAAAIAAgBIgCgNIgIgIIAAAAQgBAAAAgBQgBAAAAgBQAAAAgBAAQgBAAAAAAIAAAAIgCAAIg7gFIgEgBIAAAAQgEgBgCgCIAAAAQgBgCgBgFIAAAAIAAgEIAMmCIADgGIAAAAIAEgCIAAAAIADgBIAAAAIK6iHIAEAAQAEABACADIAAAAQADAEAAADIAAAAIAAABIAAAAIAAABIAAAAIgEJKIgBAFQgCAFgEADIAAAAQgDADgFAAIAAAAIgDgBIiAgOQgKAAgEADIAAAAQgEACgFAGIAAAAIgEAMIgCADIgGAGIAAAAQgCADgEAAIAAAAIAAAAg");
	var mask_2_graphics_48 = new cjs.Graphics().p("ACvE8IgEgBIm2g3QgFABgDgCIAAAAIgDgDIAAAAIABgBIgDgNIgIgIIAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBgBAAAAIAAAAIgCAAIg7gEIgEgBIAAAAQgFgBgBgCIAAAAQgCgCAAgFIAAAAIAAgEIAMmAIADgGIAAAAIAEgCIAAAAIADgBIAAAAIK3iGIADAAQAEABACADIAAAAQADAEAAADIAAAAIAAABIAAAAIAAABIAAAAIgEJHIgBAEQgCAGgEADIAAAAQgDADgFgBIAAAAIgDgBIh/gNQgKAAgEACIAAAAQgEACgFAGIAAAAIgEANIgCADIgGAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_49 = new cjs.Graphics().p("ACuE6IgDAAIm1g3QgEABgEgDIAAAAIgCgDIAAAAIAAgBIgCgNIgIgHIAAAAQgBgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIAAAAIgCAAIg7gFIgDAAIAAAAQgFgCgBgCIAAAAQgCgCAAgEIAAAAIgBgEIANl+IADgGIAAAAIAEgCIAAAAIADgBIAAAAIKziFIADAAQAEAAACAEIAAAAQADADAAADIAAAAIABACIAAAAIgBAAIAAAAIgEJEIgBAFQgCAFgEADIAAAAQgDADgEAAIAAAAIgEgBIh+gOQgKAAgEADIAAAAQgEACgFAGIAAAAIgEAMIgCADIgGAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_50 = new cjs.Graphics().p("ACtE5IgDgBImyg3QgFABgDgCIAAAAIgDgDIAAAAIAAgBIgCgNIgIgIIAAAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAIAAAAIgBAAIg7gFIgEAAIAAAAQgEgCgBgCIAAAAQgCgCAAgEIAAAAIgBgEIANl8IACgGIAAAAIAFgCIAAAAIACgBIAAAAIKwiFIADAAQAEABACADIAAAAQADAEABADIAAAAIAAABIAAAAIAAABIAAAAIgEJBIgCAFQgCAFgDADIAAAAQgEADgEgBIAAAAIgEgBIh9gNQgKAAgEACIAAAAQgEACgFAGIAAAAIgEANIgCADIgGAFIAAAAQgCADgDAAIAAAAIgBAAg");
	var mask_2_graphics_51 = new cjs.Graphics().p("ACsE3IgDAAImwg3QgFABgDgCIAAAAIgCgDIAAAAIAAgBIgDgNIgIgIIAAAAQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAIAAAAIgCAAIg6gFIgEAAIAAAAQgEgCgCgCIAAAAQgBgCgBgEIAAAAIAAgEIANl6IACgGIAAAAIAEgDIAAAAIADAAIAAAAIKsiEIAEAAQADAAADAEIAAAAQACADABADIAAAAIAAACIAAAAIAAAAIAAAAIgEI/IgCAEQgCAFgDADIAAAAQgEADgEAAIAAAAIgDgBIh9gOQgKAAgEADIAAAAQgEACgFAGIAAAAIgEAMIgCADIgGAGIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_52 = new cjs.Graphics().p("ACrE2IgDgBImug2QgFABgDgCIAAAAIgCgDIAAAAIAAgBIgCgNIgIgIIAAAAQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIg6gFIgDgBIAAAAQgFgBgBgCIAAAAQgBgCgBgEIAAAAIAAgEIAMl5IADgFIAAAAIAEgDIAAAAIADAAIAAAAIKpiEIADAAQAEABACADIAAAAIADAHIAAAAIAAABIAAAAIAAABIAAAAIgEI7IgBAFQgCAFgEADIAAAAQgDADgEgBIAAAAIgEgBIh8gNQgKAAgEADIAAAAQgEACgFAFIAAAAIgEANIgCADIgFAGIAAAAQgDACgDAAIAAAAIgBAAg");
	var mask_2_graphics_53 = new cjs.Graphics().p("ACrE0IgEAAImsg2QgEABgEgDIAAAAIgCgCIAAAAIAAgBIgCgNIgIgIIAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAAAIgBAAIg6gFIgEAAIAAAAQgEgCgBgCIAAAAQgCgCAAgEIAAAAIgBgEIANl3IACgGIAAAAIAEgCIAAAAIADgBIAAAAIKmiCIADAAQAEAAADAEIAAAAIADAGIAAAAIAAABIAAAAIAAABIAAAAIgEI5IgCAFQgCAFgDADIAAAAQgEADgEgBIAAAAIgDgBIh8gNQgKAAgEACIAAAAQgEADgFAFIAAAAIgDANIgDACIgFAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_54 = new cjs.Graphics().p("ACqEzIgDgBImrg1QgEABgDgDIAAAAIgDgCIAAAAIAAgCIgCgMIgIgIIAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQgBAAAAAAIAAAAIgCAAIg6gFIgDAAIAAAAQgEgCgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMl1IADgGIAAAAIAEgCIAAAAIACgBIAAAAIKkiCIADAAQAEAAACAEIAAAAIADAGIAAAAIAAACIAAAAIAAAAIAAAAIgEI3IgBAFQgCAFgEADIAAAAQgDACgEAAIAAAAIgEgBIh7gNQgKAAgEACIAAAAQgEACgEAGIAAAAIgEAMIgDADIgFAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_55 = new cjs.Graphics().p("ACpEyIgDgBImpg1QgEABgDgDIAAAAIgDgCIAAAAIAAgBIgCgNIgIgIIAAAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAIAAAAIgCAAIg5gFIgEAAIAAAAQgEgBgCgCIAAAAQgBgCgBgFIAAAAIAAgDIAMl1IADgFIAAAAIAEgDIAAAAIADAAIAAAAIKgiCIAEAAQADABADADIAAAAIADAGIAAAAIAAACIAAAAIAAAAIAAAAIgEI1IgCAEQgCAFgDADIAAAAQgDADgEAAIAAAAIgEgBIh7gNQgKAAgEACIAAAAQgDACgFAGIAAAAIgEAMIgCADIgGAGIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_56 = new cjs.Graphics().p("ACpExIgEgBImng1QgEABgDgDIAAAAIgDgCIAAAAIAAgBIgCgNIgIgHIAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIAAAAIgCAAIg5gEIgEgBIAAAAQgEgBgBgCIAAAAQgCgCAAgEIAAAAIgBgEIANlzIACgGIAAAAIAEgCIAAAAIADAAIAAAAIKeiCIADAAQAEABACADIAAAAIADAGIAAAAIABACIAAAAIAAABIAAAAIgEIyIgCAEQgCAFgDADIAAAAQgEADgEAAIAAAAIgDgBIh6gNQgKAAgEACIAAAAQgEACgFAGIAAAAIgEAMIgCADIgFAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_57 = new cjs.Graphics().p("ACoEwIgDgBImmg1QgEABgDgCIAAAAIgDgDIAAAAIAAgBIgCgNIgIgHIAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBIAAAAIgCAAIg5gEIgEgBIAAAAQgEgBgBgCIAAAAQgCgCAAgEIAAAAIAAgEIAMlxIACgGIAAAAIAEgCIAAAAIADgBIAAAAIKciBIADAAQAEABACADIAAAAIADAGIAAAAIAAACIAAAAIAAABIAAAAIgEIwIgBAEQgCAFgDADIAAAAQgEADgEAAIAAAAIgDgBIh6gNQgKAAgEACIAAAAQgEACgEAGIAAAAIgEAMIgDADIgFAGIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_58 = new cjs.Graphics().p("ACoEvIgEgBImkg1QgFABgDgCIAAAAIgCgDIAAAAIAAgBIgCgMIgIgIIAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQgBAAAAAAIAAAAIgCAAIg5gFIgDgBIAAAAQgEgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMlwIACgFIAAAAIAEgDIAAAAIADAAIAAAAIKaiBIADAAQAEABACADIAAAAIADAGIAAAAIAAACIAAAAIAAABIAAAAIgEIuIgBAFQgCAFgEACIAAAAQgDADgEAAIAAAAIgDgBIh6gNQgKAAgEACIAAAAQgDACgFAGIAAAAIgEAMIgCADIgFAGIAAAAQgDACgDAAIAAAAIAAAAg");
	var mask_2_graphics_59 = new cjs.Graphics().p("ACnEuIgDgBImjg0QgFAAgDgCIAAAAIgCgDIAAAAIAAgBIgCgMIgIgIIAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAIAAAAIgCAAIg5gEIgDgBIAAAAQgEgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMlvIACgGIAAAAIAEgCIAAAAIADgBIAAAAIKYiAIADAAQAEABACADIAAAAIADAGIAAAAIAAACIAAAAIAAAAIAAAAIgEItIgBAFQgCAFgEADIAAAAQgDACgEAAIAAAAIgDgBIh5gNQgKAAgEACIAAAAQgEADgFAFIAAAAIgDAMIgDADIgFAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_60 = new cjs.Graphics().p("ACnEtIgEgBImhg0QgFABgDgDIAAAAIgCgCIAAAAIAAgBIgDgNIgHgHIAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBgBIAAAAIgCAAIg4gEIgDgBIAAAAQgEgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMluIACgFIAAAAIAEgDIAAAAIADAAIAAAAIKWiAIADAAQAEAAACAEIAAAAIADAGIAAAAIAAABIAAAAIAAABIAAAAIgEIsIgBAEQgCAFgEADIAAAAQgDADgEgBIAAAAIgDgBIh5gNQgKAAgEADIAAAAQgDACgFAFIAAAAIgEAMIgCADIgFAGIAAAAQgDACgDAAIAAAAIAAAAg");
	var mask_2_graphics_61 = new cjs.Graphics().p("ACmEsIgDAAImhg1QgEABgDgCIAAAAIgDgDIAAAAIAAgBIgCgMIgIgIIAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIg4gFIgEAAIAAAAQgEgCgBgBIAAAAQgBgCgBgFIAAAAIAAgDIAMltIACgGIAAAAIAEgCIAAAAIADgBIAAAAIKUh/IADAAQAEAAACAEIAAAAIADAGIAAAAIAAABIAAAAIAAABIAAAAIgEIqIgBAEQgCAFgDADIAAAAQgEADgEAAIAAAAIgDgBIh5gNQgJAAgEACIAAAAQgEACgFAGIAAAAIgDAMIgDADIgFAFIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_62 = new cjs.Graphics().p("ACmEsIgDgBImgg0QgFAAgDgCIAAAAIgCgDIAAAAIAAgBIgCgMIgIgHIAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAAAgBIAAAAIgCAAIg4gEIgEgBIAAAAQgEgBgBgCIAAAAQgCgCAAgEIAAAAIgBgEIANlsIACgGIAAAAIAEgCIAAAAIADAAIAAAAIKSh/IADgBQAEABACADIAAAAIADAGIAAAAIABACIAAAAIgBABIAAAAIgDIoIgCAFQgCAFgDACIAAAAQgEADgDAAIAAAAIgEgBIh4gNQgKAAgEACIAAAAQgDADgFAFIAAAAIgEAMIgCADIgFAFIAAAAQgCADgEAAIAAAAIAAAAg");
	var mask_2_graphics_63 = new cjs.Graphics().p("AClErIgDgBImfg0QgEABgDgCIAAAAIgDgDIAAAAIABgBIgDgMIgHgIIAAAAQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIAAAAIgCAAIg4gFIgDAAIAAAAQgEgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMlsIADgFIAAAAIAEgDIAAAAIACAAIAAAAIKSh/IADAAQADABADADIAAAAIADAGIAAAAIAAABIAAAAIAAABIAAAAIgEIoIgBAEQgDAFgDADIAAAAQgDADgEgBIAAAAIgDgBIh4gMQgKAAgEACIAAAAQgEACgEAFIAAAAIgEAMIgDADIgFAGIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_64 = new cjs.Graphics().p("AClEqIgDAAImeg0QgFABgDgDIAAAAIgCgDIAAAAIAAgBIgCgMIgIgHIAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIAAAAIgCAAIg4gFIgEgBIAAAAQgDgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMlqIACgGIAAAAIAEgCIAAAAIADgBIAAAAIKQh+IADAAQAEAAACADIAAAAIADAHIAAAAIAAABIAAAAIAAABIAAAAIgEImIgBAFQgCAFgDACIAAAAQgEADgEAAIAAAAIgDgBIh4gNQgKAAgDACIAAAAQgEADgFAFIAAAAIgDAMIgDADIgFAFIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_65 = new cjs.Graphics().p("AClEqIgDgBImeg0QgEABgDgCIAAAAIgDgDIAAAAIAAgBIgCgMIgHgIIAAAAQgBAAAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIAAAAIgCAAIg3gEIgEgBIAAAAQgEgBgBgCIAAAAQgCgCAAgEIAAAAIgBgEIAMlqIADgGIAAAAIAEgCIAAAAIACAAIAAAAIKPh/IAEAAQADABADADIAAAAIACAGIAAAAIABABIAAAAIAAABIAAAAIgEImIgCAEQgCAFgDADIAAAAQgDADgEgBIAAAAIgEgBIh3gMQgKAAgEACIAAAAQgDACgFAFIAAAAIgEAMIgCADIgFAGIAAAAQgCACgEAAIAAAAIAAAAg");
	var mask_2_graphics_66 = new cjs.Graphics().p("AClEqIgEgBImcg0QgFABgDgCIAAAAIgCgDIAAAAIAAgBIgDgMIgHgIIAAAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAAAIAAAAIgCAAIg4gFIgEAAIAAAAQgDgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMlqIACgFIAAAAIAEgDIAAAAIADAAIAAAAIKOh+IADgBQAEABACADIAAAAIADAGIAAAAIAAACIAAAAIAAABIAAAAIgEIlIgBAEQgCAFgDADIAAAAQgEACgEAAIAAAAIgDgBIh3gNQgKAAgEADIAAAAQgEACgEAFIAAAAIgEAMIgCADIgFAFIAAAAQgDADgDAAIAAAAIAAAAg");
	var mask_2_graphics_67 = new cjs.Graphics().p("ACkEpIgDAAImcg0QgFABgDgDIAAAAIgCgDIAAAAIAAgBIgCgMIgIgHIAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIAAAAIgCAAIg4gFIgDgBIAAAAQgEgBgCgCIAAAAQgBgBAAgFIAAAAIgBgDIAMlqIADgFIAAAAIAEgDIAAAAIACAAIAAAAIKOh+IADAAQADAAADAEIAAAAIADAGIAAAAIAAABIAAAAIAAABIAAAAIgEIkIgBAFQgDAEgDADIAAAAQgDADgEAAIAAAAIgDgBIh4gNQgJAAgEACIAAAAQgEACgEAGIAAAAIgEAMIgDADIgFAFIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_68 = new cjs.Graphics().p("ACkEpIgDgBImcgzQgEAAgEgCIAAAAIgCgDIAAAAIAAgBIgCgMIgHgHIAAAAQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBgBIAAAAIgCAAIg3gEIgEgBIAAAAQgEgBgBgCIAAAAQgCgCAAgEIAAAAIgBgDIANlqIACgFIAAAAIAEgCIAAAAIADgBIAAAAIKMh+IAEAAQADABACADIAAAAIADAGIAAAAIABABIAAAAIgBABIAAAAIgDIkIgCAEQgCAFgDADIAAAAQgDADgEgBIAAAAIgEAAIh3gNQgKAAgDACIAAAAQgEACgFAGIAAAAIgDAMIgDACIgFAGIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_69 = new cjs.Graphics().p("ACkEpIgDgBImcg0QgEABgDgCIAAAAIgDgDIAAAAIAAgBIgCgMIgHgHIAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIAAAAIgCAAIg3gEIgEgBIAAAAQgEgBgBgCIAAAAQgBgCgBgEIAAAAIAAgEIAMlpIACgFIAAAAIAEgCIAAAAIADgBIAAAAIKMh+IADAAQAEABACADIAAAAIADAGIAAAAIAAACIAAAAIAAAAIAAAAIgEIkIgBAEQgCAFgDADIAAAAQgEADgEgBIAAAAIgDgBIh3gMQgKAAgDACIAAAAQgEACgFAFIAAAAIgDAMIgDADIgFAGIAAAAQgCACgDAAIAAAAIgBAAg");
	var mask_2_graphics_70 = new cjs.Graphics().p("ACkEpIgDgBImcg0QgEABgDgCIAAAAIgDgDIAAAAIABgBIgDgMIgHgHIAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIAAAAIgBAAIg4gEIgEgBIAAAAQgDgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMlpIACgFIAAAAIAEgCIAAAAIADgBIAAAAIKMh+IADAAQAEABACADIAAAAIADAGIAAAAIAAACIAAAAIAAAAIAAAAIgEIkIgBAEQgCAFgDADIAAAAQgEADgEgBIAAAAIgDgBIh3gMQgKAAgEACIAAAAQgDACgFAFIAAAAIgEAMIgCADIgFAFIAAAAQgCADgDAAIAAAAIgBAAg");
	var mask_2_graphics_71 = new cjs.Graphics().p("ACkEpIgDgBImcg0QgEABgDgCIAAAAIgDgDIAAAAIABgBIgDgMIgHgHIAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIAAAAIgBAAIg4gEIgEgBIAAAAQgDgBgCgCIAAAAQgBgCgBgEIAAAAIAAgEIAMloIACgGIAAAAIAEgCIAAAAIADgBIAAAAIKMh+IADAAQAEABACADIAAAAIADAGIAAAAIAAACIAAAAIAAAAIAAAAIgEIkIgBAEQgCAFgDADIAAAAQgEADgEgBIAAAAIgDgBIh3gNQgKAAgEADIAAAAQgDACgFAFIAAAAIgEAMIgCADIgFAFIAAAAQgCADgDAAIAAAAIgBAAg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:146.9285,y:13.0508}).wait(1).to({graphics:mask_2_graphics_1,x:148.1408,y:13.4098}).wait(1).to({graphics:mask_2_graphics_2,x:149.3356,y:13.764}).wait(1).to({graphics:mask_2_graphics_3,x:150.5135,y:14.1128}).wait(1).to({graphics:mask_2_graphics_4,x:151.6745,y:14.4566}).wait(1).to({graphics:mask_2_graphics_5,x:152.818,y:14.795}).wait(1).to({graphics:mask_2_graphics_6,x:153.9442,y:15.1288}).wait(1).to({graphics:mask_2_graphics_7,x:155.0533,y:15.4568}).wait(1).to({graphics:mask_2_graphics_8,x:156.1454,y:15.7804}).wait(1).to({graphics:mask_2_graphics_9,x:157.2201,y:16.099}).wait(1).to({graphics:mask_2_graphics_10,x:158.2772,y:16.4118}).wait(1).to({graphics:mask_2_graphics_11,x:159.318,y:16.72}).wait(1).to({graphics:mask_2_graphics_12,x:160.3409,y:17.0233}).wait(1).to({graphics:mask_2_graphics_13,x:161.3467,y:17.3208}).wait(1).to({graphics:mask_2_graphics_14,x:162.3358,y:17.6141}).wait(1).to({graphics:mask_2_graphics_15,x:163.307,y:17.9013}).wait(1).to({graphics:mask_2_graphics_16,x:164.2614,y:18.1843}).wait(1).to({graphics:mask_2_graphics_17,x:165.1988,y:18.4615}).wait(1).to({graphics:mask_2_graphics_18,x:166.1187,y:18.7342}).wait(1).to({graphics:mask_2_graphics_19,x:167.0214,y:19.0014}).wait(1).to({graphics:mask_2_graphics_20,x:167.907,y:19.2638}).wait(1).to({graphics:mask_2_graphics_21,x:168.7753,y:19.5208}).wait(1).to({graphics:mask_2_graphics_22,x:169.6265,y:19.7732}).wait(1).to({graphics:mask_2_graphics_23,x:170.4604,y:20.0202}).wait(1).to({graphics:mask_2_graphics_24,x:171.2772,y:20.2619}).wait(1).to({graphics:mask_2_graphics_25,x:172.0773,y:20.499}).wait(1).to({graphics:mask_2_graphics_26,x:172.8591,y:20.7303}).wait(1).to({graphics:mask_2_graphics_27,x:173.6247,y:20.9572}).wait(1).to({graphics:mask_2_graphics_28,x:174.3726,y:21.1785}).wait(1).to({graphics:mask_2_graphics_29,x:175.1032,y:21.3949}).wait(1).to({graphics:mask_2_graphics_30,x:175.8169,y:21.6064}).wait(1).to({graphics:mask_2_graphics_31,x:176.5135,y:21.8125}).wait(1).to({graphics:mask_2_graphics_32,x:177.1928,y:22.0141}).wait(1).to({graphics:mask_2_graphics_33,x:177.8546,y:22.2099}).wait(1).to({graphics:mask_2_graphics_34,x:178.4994,y:22.4011}).wait(1).to({graphics:mask_2_graphics_35,x:179.1272,y:22.5866}).wait(1).to({graphics:mask_2_graphics_36,x:179.7376,y:22.7675}).wait(1).to({graphics:mask_2_graphics_37,x:180.3306,y:22.9433}).wait(1).to({graphics:mask_2_graphics_38,x:180.907,y:23.1139}).wait(1).to({graphics:mask_2_graphics_39,x:181.4656,y:23.2795}).wait(1).to({graphics:mask_2_graphics_40,x:182.0071,y:23.4397}).wait(1).to({graphics:mask_2_graphics_41,x:182.5318,y:23.5954}).wait(1).to({graphics:mask_2_graphics_42,x:183.0389,y:23.7457}).wait(1).to({graphics:mask_2_graphics_43,x:183.5292,y:23.8906}).wait(1).to({graphics:mask_2_graphics_44,x:184.002,y:24.0305}).wait(1).to({graphics:mask_2_graphics_45,x:184.4578,y:24.1655}).wait(1).to({graphics:mask_2_graphics_46,x:184.8961,y:24.2952}).wait(1).to({graphics:mask_2_graphics_47,x:185.3174,y:24.4198}).wait(1).to({graphics:mask_2_graphics_48,x:185.7214,y:24.5399}).wait(1).to({graphics:mask_2_graphics_49,x:186.1085,y:24.6542}).wait(1).to({graphics:mask_2_graphics_50,x:186.478,y:24.7636}).wait(1).to({graphics:mask_2_graphics_51,x:186.8307,y:24.8684}).wait(1).to({graphics:mask_2_graphics_52,x:187.166,y:24.9675}).wait(1).to({graphics:mask_2_graphics_53,x:187.4842,y:25.0619}).wait(1).to({graphics:mask_2_graphics_54,x:187.7852,y:25.1506}).wait(1).to({graphics:mask_2_graphics_55,x:188.0687,y:25.2352}).wait(1).to({graphics:mask_2_graphics_56,x:188.3352,y:25.3139}).wait(1).to({graphics:mask_2_graphics_57,x:188.5844,y:25.3876}).wait(1).to({graphics:mask_2_graphics_58,x:188.8168,y:25.4565}).wait(1).to({graphics:mask_2_graphics_59,x:189.0318,y:25.52}).wait(1).to({graphics:mask_2_graphics_60,x:189.2293,y:25.579}).wait(1).to({graphics:mask_2_graphics_61,x:189.4098,y:25.6321}).wait(1).to({graphics:mask_2_graphics_62,x:189.5735,y:25.6807}).wait(1).to({graphics:mask_2_graphics_63,x:189.7195,y:25.7239}).wait(1).to({graphics:mask_2_graphics_64,x:189.8486,y:25.762}).wait(1).to({graphics:mask_2_graphics_65,x:189.9602,y:25.7953}).wait(1).to({graphics:mask_2_graphics_66,x:190.0546,y:25.8229}).wait(1).to({graphics:mask_2_graphics_67,x:190.1325,y:25.8458}).wait(1).to({graphics:mask_2_graphics_68,x:190.1923,y:25.8637}).wait(1).to({graphics:mask_2_graphics_69,x:190.2356,y:25.8768}).wait(1).to({graphics:mask_2_graphics_70,x:190.2612,y:25.8841}).wait(1).to({graphics:mask_2_graphics_71,x:190.2621,y:25.8004}).wait(75));

	// HL
	this.instance_4 = new lib.HL();
	this.instance_4.setTransform(247.75,70.15,0.5555,0.5555,0,0,0,298,0.1);

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:324.55,y:62.8},96,cjs.Ease.quadOut).wait(50));

	// PLATE
	this.instance_5 = new lib.PLATE();
	this.instance_5.setTransform(148.45,14.55,0.2542,0.2542,0,0,0,0.4,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({regX:1,regY:0.7,scaleX:0.1569,scaleY:0.1569,x:188.45,y:26.9},71,cjs.Ease.quadOut).wait(75));

	// BKGD
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("A4/D6IAAnzMAx/AAAIAAHzg");
	this.shape_1.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(146));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(114.5,-18.5,205.5,254.6);
// library properties:
lib.properties = {
	id: '0E11E9F5D49240C6BBEEAC80F63F5DAC',
	width: 320,
	height: 50,
	fps: 24,
	color: "#CCCCCC",
	opacity: 1.00,
	manifest: [
		{src:"images/REV659_Wave2_Awareness_320x50_atlas_1.png", id:"REV659_Wave2_Awareness_320x50_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0E11E9F5D49240C6BBEEAC80F63F5DAC'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;