(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"REV659_Wave2_Awareness_300x600_atlas_1", frames: [[0,0,810,456],[0,458,1000,300]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._300x600A1_CA_WHT = function() {
	this.initialize(ss["REV659_Wave2_Awareness_300x600_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.plateHL2 = function() {
	this.initialize(ss["REV659_Wave2_Awareness_300x600_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.RevivierLogorevsvg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// RevivierLogo_rev_svg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AByCaQgGAAgCgCIgFgEIhtiRIBCAAQAXAAAJgJQAJgJAAgUIAAgSQAAgUgJgKQgJgJgXAAIiiAAQgFAAAAAFIAADnQAAAKgKAAIgvAAQgLAAAAgKIAAkbQAAgOAOAAIDrAAQAzAAAWAXQAWAXAAAtIAAAZQAAAlgQAVQgPAWgjAHIBLBcIAAABQADACgCAEQAAAFgHAAg");
	this.shape.setTransform(253.9281,15.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABxCaQgFAAgDgCIgEgEIhuiRIBDAAQAWAAAKgJQAJgJAAgUIAAgSQAAgUgJgKQgKgJgWAAIiiAAQgGAAAAAFIAADnQAAAKgJAAIgwAAQgKAAAAgKIAAkbQAAgOANAAIDsAAQAyAAAWAXQAWAXAAAtIAAAZQAAAlgPAVQgPAWgjAHIBLBcIAAABQACACgBAEQAAAFgHAAg");
	this.shape_1.setTransform(17.755,15.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnCaQghAAgYgGQgZgHgNgNQgOgOgIgWQgHgVAAghIAAhLQAAgfAHgWQAIgWAOgOQAPgOAXgGQAXgHAiAAIDAAAQALAAAAAKIAAAqQAAAJgLAAIi/AAQgRAAgLADQgMAEgGAGQgGAGgEAMQgCAOAAAPIAAAEID3AAQAKAAAAAKIAAAiQAAAJgKAAIj3AAIAAAIQAAAPACAOQAEAMAGAGQAGAGAMAEQALADARAAIC/AAQALAAAAAJIAAAqQAAAKgLAAg");
	this.shape_2.setTransform(210.5,15.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJCZQgRAAgLgGQgMgIgKgTIiTkHQgCgDABgEQACgCAFgBIA4AAIAGABIAEAFICBDrQACAEADgBIABAAQADABACgEIB/jrQADgFAHgBIA6AAQAFABACACQABADgDAEIiQEHQgKAUgMAHQgKAGgOAAg");
	this.shape_3.setTransform(167.4726,15.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXCZQgKAAAAgJIAAkfQAAgKAKAAIAvAAQAKAAAAAKIAAEfQAAAJgKAAg");
	this.shape_4.setTransform(135.3,15.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJCZQgRAAgLgGQgMgIgKgTIiSkHQgDgDABgEQACgCAFgBIA4AAIAGABIAEAFICBDrQACAEADgBIABAAQAEABABgEIB/jrQADgFAIgBIA5AAQAFABACACQABADgDAEIiQEHQgLAUgLAHQgKAGgOAAg");
	this.shape_5.setTransform(103.125,15.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnCaQghAAgYgGQgZgHgNgNQgOgOgIgWQgHgVAAghIAAhLQAAgfAHgWQAIgWAOgOQAPgOAXgGQAXgHAiAAIDAAAQALAAAAAKIAAAqQAAAJgLAAIi/AAQgRAAgLADQgLADgHAHQgGAGgEAMQgCAOAAAPIAAAEID3AAQAKAAAAAKIAAAiQAAAJgKAAIj3AAIAAAIQAAAPACAOQAEAMAGAGQAGAGAMAEQALADARAAIC/AAQALAAAAAJIAAAqQAAAKgLAAg");
	this.shape_6.setTransform(57.95,15.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAJASIAAgUIgHANIgDAAIgHgNIAAAUIgIAAIAAgkIAHAAIAJAUIAKgUIAHAAIAAAkg");
	this.shape_7.setTransform(282.425,2.15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDASIAAgdIgJAAIAAgHIAZAAIAAAHIgKAAIAAAdg");
	this.shape_8.setTransform(278.875,2.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgaAyIAAhjIA1AAIAAALIgoAAIAAAhIAkAAIAAAKIgkAAIAAAiIAoAAIAAALg");
	this.shape_9.setTransform(267.3,47.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAyIAAhYIgbAAIAAgLIBDAAIAAALIgbAAIAABYg");
	this.shape_10.setTransform(253.725,47.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAeAyIgIgXIgrAAIgIAXIgOAAIAlhiIAOAAIAkBigAgRARIAjAAIgSgxg");
	this.shape_11.setTransform(239.125,47.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXAyIAAhjIANAAIAABYIAiAAIAAALg");
	this.shape_12.setTransform(225.7,47.025);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AghAyIAAhjIAhAAQARAAAIAIQAJAJAAAMQAAANgJAHQgIAIgRAAIgTAAIAAAqgAgTgBIATAAQAJAAAGgFQAGgFgBgJQAAgSgUAAIgTAAg");
	this.shape_13.setTransform(212.45,47.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaAyIAAhjIA1AAIAAALIgoAAIAAAhIAkAAIAAAKIgkAAIAAAiIAoAAIAAALg");
	this.shape_14.setTransform(188.85,47.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgQAwQgIgDgFgHQgEgHAAgHIAOAAQABAHAFAFQAFAEAIAAQALAAAEgEQAGgGAAgGQAAgGgDgEQgDgDgFgCIgMgEIgQgFQgHgCgEgFQgDgGAAgJQAAgJADgGQAEgGAIgEQAJgDAIAAQAOAAAJAHQAJAHABAMIgOAAQgBgGgFgFQgGgEgIAAQgIAAgFAEQgFAFAAAHQAAAGADADQACADAFACIANAEIAQAFQAFACAFAGQAFAGgBAJQAAAHgDAHQgEAGgIAEQgJAEgKAAQgHAAgJgDg");
	this.shape_15.setTransform(174.95,46.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAbAyIg1hPIAABPIgNAAIAAhjIANAAIA1BPIAAhPIANAAIAABjg");
	this.shape_16.setTransform(159.775,47);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaAyIAAhjIA1AAIAAALIgoAAIAAAhIAkAAIAAAKIgkAAIAAAiIAoAAIAAALg");
	this.shape_17.setTransform(145.275,47.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgXAtQgMgHgGgLQgHgMAAgOQAAgNAHgNQAGgLAMgHQALgHAOAAQARAAAMAIQAMAHAGAPIgQAAQgEgJgIgEQgHgFgMgBQgKABgIAFQgIAEgFAJQgFAKAAAKQAAALAFAKQAEAIAJAGQAKAFAIAAQAKAAAJgFQAIgFAEgJIAQAAQgGAOgMAJQgNAHgQAAQgOAAgLgGg");
	this.shape_18.setTransform(129.925,47);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgGAyIAAhjIANAAIAABjg");
	this.shape_19.setTransform(116.825,47.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgXAyIAAhjIANAAIAABYIAiAAIAAALg");
	this.shape_20.setTransform(106.525,47.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgXAyIAAhjIANAAIAABYIAiAAIAAALg");
	this.shape_21.setTransform(84.775,47.025);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAeAyIgIgXIgrAAIgJAXIgNAAIAlhiIANAAIAlBigAgSARIAkAAIgSgxg");
	this.shape_22.setTransform(70.55,47.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgFAyIAAhYIgcAAIAAgLIBDAAIAAALIgcAAIAABYg");
	this.shape_23.setTransform(55.9,47.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgGAyIAAhjIANAAIAABjg");
	this.shape_24.setTransform(44.4,47.025);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgYAtQgMgIgHgKQgGgMAAgPQAAgOAGgLQAHgMAMgGQAMgHAMAAQARAAAMAIQAMAIAGAOIgQAAQgEgJgIgEQgIgFgLAAQgJAAgJAFQgIAFgFAIQgFAJAAALQAAAMAFAJQAFAIAIAGQAJAEAJAAQAQAAAJgJQAJgJACgOIgnAAIAAgKIA1AAIAAAJQgBANgHAKQgHAKgKAGQgLAGgOAAQgLAAgNgGg");
	this.shape_25.setTransform(31.175,47);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgGAyIAAhjIANAAIAABjg");
	this.shape_26.setTransform(17.925,47.025);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgqAyIAAhjIAgAAQAQAAALAGQANAHAGALQAGALABAOQgBAQgGALQgGALgNAGQgKAGgRAAgAgcAnIASAAQATAAAJgKQALgKAAgTQAAgRgLgLQgJgKgTAAIgSAAg");
	this.shape_27.setTransform(5.45,47.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,284.1,52.1);


(lib.PLATE = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib._300x600A1_CA_WHT();
	this.instance.setTransform(-405,-228);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.PLATE, new cjs.Rectangle(-405,-228,810,456), null);


(lib.HL = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.plateHL2();
	this.instance.setTransform(177.95,-245,0.1779,1.6333,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HL, new cjs.Rectangle(0.1,-245,177.9,490), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiLIuQgcgQgQgcQgOgcAAgkQAAglAOgdQAPgcAcgPQAbgPAjAAQAjAAAbAPQAaAPAOAbQAPAbAAAiIgBAYIivAAQADAaAPAOQARAPAXAAQAhAAAPgdIBAAAQgLAjgbAWQgeAWgrAAQgiAAgbgPgAgXGrQAAgXgRgOQgQgOgXAAQgXAAgPANQgQAOgDAYIBxAAIAAAAgAo1IuQgcgQgPgcQgPgcgBgkQABglAPgdQAPgcAbgPQAbgPAjAAQAjAAAaAPQAbAPAPAbQAPAbAAAiIgCAYIivAAQADAaAQAOQAPAPAYAAQAhAAAPgdIBBAAQgKAjgdAWQgeAWgrAAQgjAAgagPgAnAGrQgBgXgQgOQgRgOgYAAQgWAAgPANQgPAOgEAYIByAAIAAAAgAyUIzQgXgLgOgSQgNgSgBgWIA8AAQACAOAMAJQAMAJARAAQARAAAKgHQAKgHAAgLQAAgMgMgGQgMgFgZgHQgbgHgRgGQgSgHgLgPQgNgOAAgYQAAgUALgQQAMgRAVgJQAWgKAdAAQAqAAAZAWQAaAVADAkIg6AAQgCgOgKgIQgLgJgRAAQgRAAgIAGQgJAGAAALQAAAMAMAGQAMAHAZAGQAaAHARAHQARAGAMAPQANAOAAAYQAAAVgMAQQgLAQgVAKQgWAJgdAAQgcAAgYgKgABMIyQgLgKAAgPQAAgPALgKQAKgLAQAAQARAAAKALQAKAKAAAPQAAAPgKAKQgKAKgRAAQgQAAgKgKgAldI5IAAjvIA8AAIAAAlQAMgTATgLQASgKAZAAIAAA/IgQAAQgdAAgOAOQgPANAAAhIAAB3gArPI5IAAiEQAAgcgOgQQgOgPgZAAQgZAAgPAPQgOAQAAAcIAACEIg9AAIAAk/IA9AAIAABuQAMgQASgIQAVgJAXAAQAbAAAVALQAWANALAWQAMAYAAAgIAACMgA0sI5IAAjvIA9AAIAADvgA0nEjQgKgKAAgPQAAgPAKgKQALgKAQAAQAQAAAKAKQAKAKABAPQgBAPgKAKQgKALgQAAQgQAAgLgLgAESEZIAAlgIA9AAIAAAjQALgRAVgLQAUgLAbAAQAeAAAZAPQAZAPAOAcQAPAbAAAlQAAAlgPAcQgOAcgZAQQgZAPgeAAQgaAAgVgLQgUgKgMgRIAACUgAFvgNQgPAIgIAPQgKAQABAWQgBAVAKAQQAIAQAPAJQAPAIAQAAQARAAAOgIQAOgJAKgQQAIgQAAgWQAAgWgIgQQgKgOgOgIQgOgJgRAAQgQAAgPAJgASJCcQgcgQgPgcQgPgcgBgkQABglAPgcQAOgcAbgPQAcgPAjAAQAiAAAbAPQAbAPAPAbQAPAaAAAiIgCAYIiuAAQACAaAQAOQAPAPAYAAQAhAAAPgdIBBAAQgKAjgeAWQgdAWgrAAQgjAAgagPgAT+AZQgBgXgQgNQgRgOgYAAQgWAAgPANQgQANgDAYIByAAIAAAAgALGCcQgZgQgPgcQgNgcAAglQAAgkANgcQAPgcAZgPQAYgPAgAAQAaAAAVALQAUALALAQIAAgiIA9AAIAADuIg9AAIAAgjQgLARgUALQgVALgbAAQgeAAgZgPgALugNQgPAIgJAOQgIAQAAAWQAAAVAIARQAJAQAPAJQAPAIAQAAQARAAAPgIQAOgJAJgQQAJgPgBgWQABgWgJgQQgJgPgOgIQgPgJgRAAQgRAAgOAJgAglCcQgcgQgPgcQgPgcAAgkQAAglAPgcQAPgcAbgPQAcgPAhAAQAjAAAbAPQAbAPAPAbQAOAaAAAiIgBAYIiuAAQACAaAQAOQAQAPAWAAQAiAAAOgdIBCAAQgLAjgdAWQgeAWgrAAQghAAgbgPgABPAZQgBgXgQgNQgRgOgXAAQgWAAgOANQgQANgDAYIBwAAIAAAAgAkNChQgXgLgNgSQgOgSgBgWIA9AAQABAOAMAJQAMAJARAAQASAAAJgHQAKgHAAgLQAAgMgMgGQgLgFgagHQgcgHgRgGQgQgHgMgPQgNgOAAgXQAAgUAMgQQALgRAVgJQAVgKAdAAQArAAAaAWQAZAVADAjIg6AAQgBgNgLgIQgKgJgSAAQgQAAgKAGQgJAGAAALQAAALAMAGQANAHAaAGQAZAHARAHQARAGAMAPQAMAOABAYQAAAVgLAQQgMAQgWAKQgUAJgeAAQgcAAgYgKgAsjCcQgbgQgPgcQgQgcABgkQgBglAQgcQAPgcAagPQAcgPAjAAQAiAAAcAPQAaAPAPAbQAPAaAAAiIgCAYIiuAAQACAaAQAOQAQAPAXAAQAhAAAPgdIBBAAQgLAjgdAWQgdAWgrAAQgjAAgbgPgAquAZQAAgXgRgNQgQgOgYAAQgWAAgPANQgQANgDAYIBxAAIAAAAgAwhCcQgagQgQgbQgPgcABglQgBglAPgbQAQgcAagPQAbgQAjAAQAsAAAdAWQAdAXAKAnIhBAAQgGgPgMgIQgLgJgTAAQgaAAgPASQgPASAAAjQAAAiAPATQAPASAaAAQAlAAALggIBBAAQgKAmgdAXQgeAXgrAAQgjAAgbgPgAQTCnQhNAAAAhKIAAhyIgcAAIAAgyIAcAAIAAg7IA+AAIAAA7IA1AAIAAAyIg1AAIAAByQAAANAFAFQAGAFAOAAIAcAAIAAAzgAIvCnIAAk+IA8AAIAAE+gAmiCnIAAiEQAAgcgPgPQgOgPgZAAQgZAAgOAPQgPAPAAAcIAACEIg9AAIAAjuIA9AAIAAAeQAMgQATgIQATgJAWAAQArAAAbAbQAaAbAAAvIAACMgAy7CnIAAjuIA9AAIAADugA0sCnIAAk+IA9AAIAAE+gAy3huQgKgKAAgPQAAgPAKgKQALgKAQAAQAQAAAKAKQALAKAAAPQAAAPgLAKQgKALgQAAQgQAAgLgLgAgTiMQgggXgFgpIA8AAQAEAQAQAKQAQAJAXAAQAZAAARgPQAQgQAAggIAAglQgMARgTALQgVALgbAAQgeAAgYgPQgZgQgOgcQgOgcgBglQABgkAOgdQAOgcAZgPQAXgPAfAAQAbAAAVALQATAKAMARIAAgiIA9AAIAADxQAAAhgNAaQgNAagbAQQgbAPgmAAQgzAAgggYgAAbmfQgOAIgJAPQgIAQAAAWQAAAVAIARQAJAQAOAJQAOAIARAAQAQAAAQgIQAOgJAJgQQAIgPAAgWQAAgWgIgQQgJgQgOgIQgQgJgQAAQgRAAgOAJgAIhj1QgZgQgOgcQgOgcAAglQAAgkAOgdQAOgcAZgPQAZgPAfAAQAbAAAUALQAUALAMAQIAAgiIA9AAIAADvIg9AAIAAgjQgMARgUALQgUALgcAAQgeAAgZgPgAJKmfQgPAIgJAPQgJAQAAAWQAAAVAJARQAJAQAPAJQAOAIAQAAQARAAAPgIQAPgJAIgQQAJgPAAgWQAAgWgJgQQgIgQgPgIQgPgJgRAAQgQAAgOAJgAmZj1QgZgQgPgcQgOgcAAglQAAgkAOgdQAPgcAZgPQAYgPAfAAQAXAAAWAKQAVAKANARIAAhxIA9AAIAAE/Ig9AAIAAgjQgMASgUAKQgUALgbAAQgfAAgYgPgAlymfQgOAIgJAPQgIAQAAAWQAAAVAIARQAJAQAOAJQAPAIARAAQAQAAAPgIQAOgJAKgQQAIgPAAgWQAAgWgIgQQgKgQgOgIQgPgJgQAAQgSAAgOAJgAr4j1QgbgQgQgcQgPgcAAgkQAAglAPgdQAPgcAbgPQAbgPAkAAQAiAAAbAPQAbAPAOAbQAPAbAAAiIgBAYIivAAQADAaAPAOQAQAPAYAAQAhAAAOgdIBBAAQgKAjgdAWQgeAWgqAAQgjAAgbgPgAqDl4QAAgXgRgOQgRgOgXAAQgWAAgPANQgQAOgEAYIByAAIAAAAgAMZjqIAAk/IA8AAIAAE/gAGxjqQhNAAAAhKIAAhzIgdAAIAAgyIAdAAIAAg7IA9AAIAAA7IA2AAIAAAyIg2AAIAABzQAAANAGAFQAGAFAOAAIAcAAIAAAzgADqjqIAAjvIA8AAIAADvgAijjqIAAjvIA8AAIAADvgAuRjqIAAiEQAAgcgPgQQgOgPgZAAQgZAAgOAPQgPAQAAAcIAACEIg9AAIAAk/IA9AAIAABuQAMgQATgIQAUgJAXAAQAcAAAVALQAVANALAWQANAYAAAgIAACMgAzrjqIAAj8IhQAAIAAgxIDdAAIAAAxIhRAAIAAD8gADuoAQgKgKAAgPQAAgPAKgKQALgKAQAAQAQAAAKAKQALAKAAAPQAAAPgLAKQgKALgQAAQgQAAgLgLgAieoAQgLgKAAgPQAAgPALgKQAKgKAQAAQAQAAALAKQAKAKAAAPQAAAPgKAKQgLALgQAAQgQAAgKgLg");
	this.shape.setTransform(138.7,70.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(4.7,13.6,268,114.6), null);


(lib.HEAD1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArwK1QgpgdgFg0IBLAAQAFAVAVAMQATAMAcAAQAhAAAUgUQAVgTAAgoIAAgvQgOAWgaAOQgaANghAAQglAAgfgTQgggTgSgkQgSgjAAguQAAgtASgjQASgjAfgTQAfgTAmAAQAiAAAZANQAaANAOAVIAAgqIBMAAIAAEtQAAApgQAhQgSAhghATQgiATgvAAQhAAAgogegAq2FdQgSAKgLATQgLAUAAAbQAAAbALAUQALAVASALQATAKATAAQAWAAASgKQATgLAKgTQALgUAAgcQAAgbgLgUQgKgUgTgKQgSgLgWAAQgUAAgSALgAEgIxQgfgTgSgkQgSgjAAguQAAgtASgjQASgjAfgTQAggTAmAAQAdAAAaANQAbAMAPAVIAAiOIBNAAIAAGQIhNAAIAAgtQgNAXgaANQgZANgiAAQglAAgggTgAFSFdQgSAKgLATQgLAUAAAbQAAAbALAUQALAVASALQATAKATAAQAWAAASgKQASgLAMgTQAKgUAAgcQAAgbgKgUQgMgUgSgKQgSgLgWAAQgUAAgSALgAgpIyQgigUgUgjQgTgjAAguQgBgtAVgjQATgkAkgTQAjgTAqAAQArAAAjATQAkATATAkQAVAjAAAtQAAAugVAjQgVAjgjAUQgkASgrAAQgqAAgjgSgAgRFpQgVAXAAAqQAAArAVAXQAUAXAhAAQAUAAATgKQARgKAMgUQAKgUAAgdQAAgqgWgXQgXgXggAAQggAAgWAXgAl6IyQgjgUgTgjQgUgjAAguQABgtATgjQAUgkAkgTQAjgTArAAQArAAAkATQAiATAVAkQAUAjAAAtQAAAugVAjQgVAjgjAUQgjASgsAAQgsAAgigSgAliFpQgVAXAAAqQAAArAVAXQAWAXAgAAQAVAAARgKQATgKAKgUQALgUAAgdQAAgqgWgXQgXgXggAAQggAAgXAXgAJXI3QgOgNAAgTQAAgTAOgMQANgNAVAAQATAAANANQANAMABATQgBATgNANQgNAMgTAAQgVAAgNgMgAF+BtQgegNgQgXQgSgXgBgbIBMAAQACARAPALQAOAMAWAAQAWAAAMgJQAMgIAAgOQABgPgQgHQgOgHghgIQghgIgWgIQgVgJgPgSQgQgSAAgeQAAgZAPgUQAOgVAagMQAcgLAjAAQA2AAAgAaQAgAbADAtIhIAAQgCgSgNgKQgNgLgXAAQgUAAgLAIQgLAIAAANQAAAPAPAIQAPAIAgAIQAgAIAVAJQAWAIAPASQAPARAAAeQABAagOAVQgPAUgaALQgbAMgkAAQgkAAgdgNgAkBBnQgigTgUgjQgTgjAAgtQgBguAVgjQAUgjAjgTQAjgTArAAQArAAAjATQAkATATAjQAVAjAAAuQAAAtgVAjQgVAjgjATQgkATgrAAQgrAAgjgTgAjphhQgVAXAAArQAAAqAVAWQAVAXAhAAQAUAAATgKQARgKAMgUQAKgTAAgcQAAgrgWgXQgXgXggAAQggAAgXAXgApSBnQgjgTgTgjQgUgjAAgtQABguATgjQAUgjAkgTQAjgTArAAQArAAAkATQAiATAUAjQAVAjAAAuQAAAtgVAjQgVAjgjATQgjATgsAAQgsAAgigTgAo6hhQgVAXAAArQAAAqAVAWQAWAXAgAAQAVAAARgKQATgKAKgUQALgTAAgcQAAgrgWgXQgXgXggAAQggAAgXAXgADKB1Ihmh+IAAB+IhMAAIAAmOIBMAAIAADjIBlh/IBiAAIiECWICFCUgAsYB1IAAmOIBMAAIAAGOgACHljQgfgTgSgkQgSgjAAguQAAgtASgjQASgjAfgTQAfgTAmAAQAiAAAZANQAZAOAPAUIAAgqIBMAAIAAErIhMAAIAAgsQgPAVgZAOQgaANghAAQgmAAgfgTgAC5o3QgSAKgLATQgLAUAAAbQAAAbALAUQALAVASALQATAKATAAQAWAAASgKQASgLAMgTQAKgUAAgcQAAgbgKgUQgMgUgSgKQgSgLgWAAQgUAAgSALgArcleQgggNgTgaQgSgZgBgjIBRAAQACAXAPAOQAPAOAaAAQAaAAAPgNQAQgNAAgUQAAgRgLgLQgKgLgPgGIgrgOQglgKgWgLQgYgKgQgWQgRgVAAgkQAAghARgZQARgZAegNQAegNAnAAQA6AAAlAcQAkAcAEAzIhTAAQgBgTgQgNQgPgNgZAAQgWAAgNAMQgNALgBAWQAAAPAKAKQAKAKAPAGIAqAOQAlALAXALQAXAKARAWQARAWAAAjQgBAegPAaQgQAageAPQgeAPgpAAQgoAAgfgNgAL8lUQhfAAAAhdIAAiQIgjAAIAAg+IAjAAIAAhKIBMAAIAABKIBDAAIAAA+IhDAAIAACRQAAAPAIAGQAHAHARAAIAjAAIAABAgAG+lUIAAkrIBLAAIAAAuQAPgYAYgNQAXgNAfAAIAABPIgVAAQgjAAgSARQgSAQgBAqIAACVgAg0lUIAAilQAAgjgSgTQgSgTgfAAQgeAAgSATQgTATABAjIAAClIhMAAIAAilQAAgjgSgTQgSgTgeAAQgfAAgTATQgSATAAAjIAAClIhMAAIAAkrIBMAAIAAAkQAOgTAYgLQAWgKAcAAQAjAAAbAOQAdAPAPAcQAOgaAcgQQAbgPAhAAQA3AAAhAhQAiAiAAA8IAACwg");
	this.shape.setTransform(86.3,92.825);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(5.1,20.5,162.4,144.7), null);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE7BGQgMgHgHgMQgGgMAAgRQAAgQAGgMQAHgMAMgHQAMgGAQAAQAQAAAMAGQALAHAHAMQAHALAAAQIgBAJIhJAAQABAKAFAFQAGAFAIAAQAMAAAFgKIAjAAQgDALgHAIQgHAIgKAFQgLAFgNAAQgPAAgNgHgAFrAMQAAgIgGgEQgGgFgIAAQgIAAgGAFQgGADgBAJIApAAIAAAAgAC9BGQgLgHgGgMQgGgNAAgQQAAgQAGgMQAGgMALgHQAKgGANAAQALAAAIAEQAJAEAFAIIAAgxIAhAAIAACLIghAAIAAgPQgFAIgIAEQgIAFgMAAQgNAAgKgHgADNADQgGAHAAAMQAAAMAGAHQAHAHAKAAQAKAAAGgHQAHgHAAgMQAAgMgHgHQgGgGgKAAQgKAAgHAGgAhIBIQgKgFgHgIQgGgIgBgLIAgAAQABAGAFADQAEAEAHAAQAGAAADgDQAEgCAAgEQAAgEgFgDIgQgEQgLgDgIgDQgHgDgGgGQgFgHAAgKQAAgJAFgHQAFgIAKgEQAJgEAOAAQAUAAALAKQAMAJACAQIgeAAQgBgFgEgDQgEgDgHAAQgGAAgDACQgDACAAADQAAAFAFACQAFACAKACIATAGQAIADAFAHQAGAGAAALQAAAKgFAHQgFAHgKAFQgKAEgNAAQgOAAgLgFgAkiBGQgMgHgHgMQgHgMAAgRQAAgQAHgMQAHgMAMgHQAMgGAQAAQAPAAAMAGQAMAHAHAMQAGALAAAQIAAAJIhKAAQABAKAGAFQAFAFAJAAQAMAAAEgKIAjAAQgDALgHAIQgHAIgKAFQgKAFgNAAQgQAAgMgHgAjzAMQAAgIgGgEQgFgFgJAAQgIAAgGAFQgFADgBAJIAoAAIAAAAgAB5BLIAAhpIAhAAIAABpgAAtBLIAAhpIAhAAIAAASQAFgJAJgFQAIgFALAAIAAAiIgJAAQgMAAgGAFQgGAFAAANIAAAxgAibBLQgSAAgJgIQgKgJAAgUIAAgpIgNAAIAAgbIANAAIAAgaIAgAAIAAAaIAVAAIAAAbIgVAAIAAAqQAAAFACACQADACAFAAIAMAAIAAAbgAmLBLIAAiEIAhAAIAABrIAqAAIAAAZgAiAgGIAKgzIAhAAIgVAzgAB7guQgFgFAAgHQAAgIAFgFQAGgFAIAAQAJAAAFAFQAGAFAAAIQAAAHgGAFQgFAFgJAAQgIAAgGgFg");
	this.shape.setTransform(0.575,-0.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// cta_box
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AoICIIAAkPIQRAAIAAEPg");
	this.shape_1.setTransform(0,0.45);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-52.1,-13.1,104.2,27.2), null);


// stage content:
(lib.REV659_Wave2_Awareness_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [145];
	// timeline functions:
	this.frame_145 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(145).call(this.frame_145).wait(1));

	// mask_idn (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgoAsg");
	var mask_graphics_91 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgoAsg");
	var mask_graphics_92 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgoAsg");
	var mask_graphics_93 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgoAsg");
	var mask_graphics_94 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgoAsg");
	var mask_graphics_95 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgoAsg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:263.8395,y:170.5721}).wait(91).to({graphics:mask_graphics_91,x:270.8392,y:170.5721}).wait(1).to({graphics:mask_graphics_92,x:357.3531,y:170.5716}).wait(1).to({graphics:mask_graphics_93,x:443.8656,y:170.5716}).wait(1).to({graphics:mask_graphics_94,x:530.3781,y:170.5716}).wait(1).to({graphics:mask_graphics_95,x:616.8892,y:170.5721}).wait(1).to({graphics:null,x:0,y:0}).wait(50));

	// HEAD1
	this.instance = new lib.HEAD1();
	this.instance.setTransform(9.7,-0.4);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},96).wait(50));

	// mask_idn_copy (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_91 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgpAsg");
	var mask_1_graphics_92 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgpAsg");
	var mask_1_graphics_93 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgpAsg");
	var mask_1_graphics_94 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgpAsg");
	var mask_1_graphics_95 = new cjs.Graphics().p("EgxBgcuMA6sgCDMACGA7gMg6tACDgEAxCAF7IgpAsg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(91).to({graphics:mask_1_graphics_91,x:-105.3554,y:156.6531}).wait(1).to({graphics:mask_1_graphics_92,x:-18.8546,y:156.6527}).wait(1).to({graphics:mask_1_graphics_93,x:67.6458,y:156.6527}).wait(1).to({graphics:mask_1_graphics_94,x:154.1462,y:156.6527}).wait(1).to({graphics:mask_1_graphics_95,x:240.6447,y:156.6531}).wait(51));

	// HEAD2
	this.instance_1 = new lib.HEAD2();
	this.instance_1.setTransform(9.7,-0.4);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(91).to({_off:false},0).wait(55));

	// CTA
	this.instance_2 = new lib.CTA();
	this.instance_2.setTransform(149.95,479,1.4,1.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(135).to({regX:0.2,regY:0.1,scaleX:1.6799,scaleY:1.6799,x:150.3,y:479.05},3,cjs.Ease.quadInOut).to({regX:0,regY:0,scaleX:1.4,scaleY:1.4,x:149.95,y:479},6,cjs.Ease.quadInOut).wait(2));

	// LOGO
	this.instance_3 = new lib.RevivierLogorevsvg("synched",0);
	this.instance_3.setTransform(157.05,550.05,0.95,0.95,0,0,0,142.2,26.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(146));

	// footer_bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bMgIAA4/MAu3AAAIAAY/g");
	this.shape.setTransform(150,520);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(146));

	// mask_idn (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("AQWdiIgUgEMgpFgFKQgdAFgTgOIAAAAQgMgJgDgJIAAAAIABgGIgPhNQghgcgOgTIAAAAQgJgMgNgDIAAAAIgMAAIlhgcQgLgBgMgEIAAAAQgZgHgJgMIAAAAQgJgMgEgbIAAAAIgCgXMABNgkBQAFgVAKgOIAAAAQAHgIASgGIAAAAIARgDIAAAAMBBBgMiIAUgBQAXAEAPAVIAAAAQAPAVADASIAAAAIACAJIAAAAIgBAEIAAAAMgAYA2lIgJAcQgNAfgVASIAAAAQgVASgZgDIAAAAIgVgGIr3hRQg+AAgYAOIAAAAQgXAOgdAiIAAAAIgYBNIgPARIghAjIAAAAQgNAPgVAAIAAAAIgDgBg");
	var mask_2_graphics_1 = new cjs.Graphics().p("AQMdQIgUgEMgosgFHQgcAFgTgOIAAAAQgMgJgCgIIAAAAIAAgHIgOhMQghgcgOgTIAAAAQgJgLgNgDIAAAAIgLAAIlfgcQgKgBgMgEIAAAAQgZgHgJgMIAAAAQgJgMgDgaIAAAAIgCgXMABLgjqQAFgWALgNIAAAAQAHgJASgFIAAAAIAQgDIAAAAMBAZgMaIAUgBQAWADAPAVIAAAAQAPAVADASIAAAAIABAIIAAAAIAAAFIAAAAMgAYA2DIgJAbQgNAfgVASIAAAAQgUASgZgDIAAAAIgVgGIrvhQQg+AAgXAOIAAAAQgYAOgcAiIAAAAIgYBLIgPASIggAiIAAAAQgOAOgUAAIAAAAIgDAAg");
	var mask_2_graphics_2 = new cjs.Graphics().p("AQCc+IgUgEMgoSgFEQgcAFgTgOIAAAAQgMgJgCgIIAAAAIAAgGIgOhLQghgcgOgTIAAAAQgIgMgNgCIAAAAIgMAAIlagcQgLgBgMgEIAAAAQgYgHgJgMIAAAAQgJgLgDgaIAAAAIgCgYMABLgjUQAEgVALgNIAAAAQAHgIARgGIAAAAIARgDIAAAAMA/xgMSIATgBQAWADAPAVIAAAAQAPAVADARIAAAAIABAJIAAAAIAAAEIAAAAMgAYA1iIgJAbQgMAegVASIAAAAQgVASgYgDIAAAAIgVgGIrnhPQg+AAgXAOIAAAAQgXANgcAiIAAAAIgYBLIgPARIgfAiIAAAAQgOAOgUAAIAAAAIgDAAg");
	var mask_2_graphics_3 = new cjs.Graphics().p("AP4csIgUgEMgn5gFAQgcAFgTgOIAAAAQgLgJgDgIIAAAAIABgHIgOhKQghgcgNgSIAAAAQgJgMgNgCIAAAAIgLAAIlXgcQgLgBgMgDIAAAAQgYgIgJgLIAAAAQgIgMgEgaIAAAAIgCgWMABKgi/QAFgVALgNIAAAAQAGgIASgFIAAAAIAQgEIAAAAMA/KgMKIATgBQAWADAPAVIAAAAQAOAUAEARIAAAAIABAJIAAAAIgBAFIAAAAMgAXA1AIgJAbQgMAegVASIAAAAQgUARgZgCIAAAAIgUgGIrhhPQg8AAgXAOIAAAAQgXANgcAhIAAAAIgYBLIgOARIggAiIAAAAQgNANgUAAIAAAAIgDAAg");
	var mask_2_graphics_4 = new cjs.Graphics().p("APucbIgTgFMgnhgE9QgcAFgSgOIAAAAQgMgIgCgJIAAAAIAAgGIgOhJQgggcgNgSIAAAAQgJgMgNgCIAAAAIgLAAIlUgcQgKgBgMgDIAAAAQgYgHgJgMIAAAAQgIgLgEgaIAAAAIgCgWMABKgipQAFgVAKgNIAAAAQAHgIARgFIAAAAIAQgEIAAAAMA+jgMDIAUgBQAVAEAPAUIAAAAQAOAUADARIAAAAIACAJIAAAAIgBAEIAAAAMgAXA0hIgJAaQgMAegVARIAAAAQgUASgYgDIAAAAIgUgGIrahOQg8AAgWAOIAAAAQgXANgcAhIAAAAIgXBKIgOARIggAhIAAAAQgNAOgUAAIAAAAIgDAAg");
	var mask_2_graphics_5 = new cjs.Graphics().p("APlcJIgTgEMgnJgE6QgcAFgSgOIAAAAQgMgJgCgIIAAAAIAAgGIgNhJQgggbgOgSIAAAAQgIgLgNgDIAAAAIgLAAIlQgbQgKgBgMgDIAAAAQgYgHgJgMIAAAAQgIgLgEgZIAAAAIgBgXMABIgiUQAFgUAKgNIAAAAQAHgIARgFIAAAAIAQgEIAAAAMA99gL7IATgBQAVADAPAUIAAAAQAOAUADARIAAAAIABAIIAAAAIAAAFIAAAAMgAXA0AIgJAaQgMAegUARIAAAAQgUARgYgCIAAAAIgUgGIrThNQg7AAgWANIAAAAQgXAOgcAgIAAAAIgWBJIgPARIgfAhIAAAAQgNANgUAAIAAAAIgCAAg");
	var mask_2_graphics_6 = new cjs.Graphics().p("APbb4IgTgEMgmxgE3QgbAFgSgOIAAAAQgMgIgCgIIAAAAIAAgHIgNhIQgggbgNgSIAAAAQgIgLgNgCIAAAAIgLAAIlNgbQgKgBgMgDIAAAAQgYgHgIgMIAAAAQgJgLgDgZIAAAAIgCgWMABIgh/QAFgVAKgMIAAAAQAHgIARgGIAAAAIAQgDIAAAAMA9XgL0IATgBQAVADAOAUIAAAAQAOAUAEARIAAAAIABAIIAAAAIgBAEIAAAAMgAWAzhIgJAaQgMAdgUARIAAAAQgUARgXgCIAAAAIgUgGIrMhMQg7AAgWANIAAAAQgXANgbAgIAAAAIgXBJIgOAQIgeAhIAAAAQgNANgUAAIAAAAIgDAAg");
	var mask_2_graphics_7 = new cjs.Graphics().p("APSboIgTgFMgmagE0QgaAFgTgOIAAAAQgLgIgCgIIAAAAIAAgGIgNhIQgggagNgSIAAAAQgIgLgMgDIAAAAIgLAAIlLgaQgJgBgMgDIAAAAQgXgHgJgMIAAAAQgIgLgEgZIAAAAIgBgWMABHghqQAFgUAKgNIAAAAQAGgIARgFIAAAAIAQgDIAAAAMA8ygLuIATgBQAVAEAOATIAAAAQAOAUADARIAAAAIABAIIAAAAIAAAEIAAAAMgAXAzCIgIAaQgMAdgUARIAAAAQgUARgXgDIAAAAIgUgFIrFhMQg6AAgWANIAAAAQgWANgbAgIAAAAIgXBHIgOARIgeAgIAAAAQgNAOgTAAIAAAAIgDAAg");
	var mask_2_graphics_8 = new cjs.Graphics().p("APJbXIgTgEMgmDgExQgaAEgSgNIAAAAQgLgIgDgIIAAAAIABgGIgOhHQgfgbgNgRIAAAAQgHgLgNgDIAAAAIgLAAIlHgaQgKgBgLgDIAAAAQgYgHgIgLIAAAAQgIgLgDgZIAAAAIgCgWMABHghWQAEgUAKgNIAAAAQAGgHARgGIAAAAIAQgDIAAAAMA8OgLmIASgBQAVADAOAUIAAAAQAOATADARIAAAAIABAIIAAAAIAAAEIAAAAMgAXAykIgIAZQgMAdgTAQIAAAAQgUARgXgCIAAAAIgTgGIq/hLQg6AAgWANIAAAAQgVANgbAgIAAAAIgXBGIgNARIgeAgIAAAAQgNANgUAAIAAAAIgCAAg");
	var mask_2_graphics_9 = new cjs.Graphics().p("APAbHIgTgEMglsgEvQgaAFgSgNIAAAAQgLgJgCgIIAAAAIAAgFIgNhHQgfgagNgRIAAAAQgIgLgMgDIAAAAIgKAAIlFgaQgJgBgMgDIAAAAQgXgHgIgLIAAAAQgIgLgEgYIAAAAIgBgWMABGghCQAEgUAKgMIAAAAQAGgIARgFIAAAAIAPgDIAAAAMA7rgLgIASgBQAVADANAUIAAAAQAOATADAQIAAAAIABAIIAAAAIAAAFIAAAAMgAWAyFIgIAZQgMAdgUAQIAAAAQgTARgXgDIAAAAIgTgFIq4hKQg5AAgWAMIAAAAQgWANgaAgIAAAAIgWBGIgOAQIgeAgIAAAAQgMANgUAAIAAAAIgCAAg");
	var mask_2_graphics_10 = new cjs.Graphics().p("AO3a3IgSgEMglWgEsQgaAFgSgOIAAAAQgLgIgCgHIAAAAIAAgGIgNhGQgegagNgRIAAAAQgIgLgMgCIAAAAIgLAAIlBgaQgJgBgMgDIAAAAQgXgHgIgLIAAAAQgIgLgDgYIAAAAIgCgVMABGggvQAEgUAKgMIAAAAQAGgIAQgFIAAAAIAQgDIAAAAMA7HgLZIASgBQAUADAOATIAAAAQAOAUADAQIAAAAIABAIIAAAAIgBAEIAAAAMgAVAxoIgJAZQgLAcgUAQIAAAAQgTARgWgDIAAAAIgTgFIqyhKQg5AAgVANIAAAAQgWANgaAfIAAAAIgWBFIgNAQIgeAgIAAAAQgMANgTAAIAAAAIgDAAg");
	var mask_2_graphics_11 = new cjs.Graphics().p("AOuanIgSgEMglAgEpQgaAFgRgNIAAAAQgLgJgCgHIAAAAIAAgGIgNhFQgegagNgRIAAAAQgHgLgNgCIAAAAIgKAAIk+gZQgKgBgLgEIAAAAQgXgGgIgLIAAAAQgIgLgDgYIAAAAIgCgVMABFggcQAFgTAJgMIAAAAQAGgIARgFIAAAAIAPgDIAAAAMA6kgLSIASgBQAVADANATIAAAAQAOATADAQIAAAAIABAIIAAAAIgBAEIAAAAMgAVAxLIgJAZQgLAcgTAQIAAAAQgTAQgXgCIAAAAIgTgGIqrhJQg4AAgVANIAAAAQgVANgbAeIAAAAIgVBFIgOAQIgdAfIAAAAQgMANgTAAIAAAAIgDAAg");
	var mask_2_graphics_12 = new cjs.Graphics().p("AOmaYIgSgEMgkrgEnQgZAFgSgNIAAAAQgKgIgDgIIAAAAIABgGIgNhEQgegZgNgRIAAAAQgHgLgMgCIAAAAIgKAAIk8gaQgJAAgMgEIAAAAQgWgGgIgLIAAAAQgIgLgDgXIAAAAIgCgVMABEggJQAFgUAJgMIAAAAQAHgHAQgFIAAAAIAPgDIAAAAMA6CgLMIASgBQAUAEANASIAAAAQAOATADAQIAAAAIABAIIAAAAIgBAEIAAAAMgAVAwuIgIAZQgMAbgTAQIAAAAQgSAQgXgCIAAAAIgSgFIqlhIQg4AAgVAMIAAAAQgVANgaAeIAAAAIgVBEIgOAQIgdAfIAAAAQgMANgTAAIAAAAIgCAAg");
	var mask_2_graphics_13 = new cjs.Graphics().p("AOdaIIgRgEMgkWgEjQgZAEgRgNIAAAAQgLgIgCgHIAAAAIAAgGIgNhDQgdgagNgQIAAAAQgHgLgMgCIAAAAIgKAAIk5gaQgJAAgLgDIAAAAQgWgHgIgLIAAAAQgIgKgDgYIAAAAIgCgVIBD/2QAFgTAJgMIAAAAQAGgIAQgEIAAAAIAPgDIAAAAMA5hgLFIASgBQAUADANASIAAAAQANATADAQIAAAAIABAIIAAAAIAAAEIAAAAMgAWAwSIgIAYQgLAbgTAQIAAAAQgSAQgWgCIAAAAIgTgFIqfhIQg3AAgVAMIAAAAQgVANgZAeIAAAAIgWBDIgNAQIgdAfIAAAAQgMAMgSAAIAAAAIgDAAg");
	var mask_2_graphics_14 = new cjs.Graphics().p("AOVZ5IgSgEMgkAgEgQgZAEgRgNIAAAAQgLgIgCgHIAAAAIAAgGIgMhDQgegZgMgRIAAAAQgHgKgMgCIAAAAIgKAAIk2gZQgJgBgLgDIAAAAQgWgHgIgKIAAAAQgIgLgDgXIAAAAIgCgVIBD/kQAFgTAJgMIAAAAQAGgHAQgFIAAAAIAPgDIAAAAMA4/gK/IASAAQAUADANASIAAAAQANASADAQIAAAAIABAIIAAAAIgBAEIAAAAMgAVAv2IgIAYQgLAcgSAPIAAAAQgTAQgWgCIAAAAIgSgFIqZhHQg3AAgUAMIAAAAQgVAMgZAeIAAAAIgWBDIgNAPIgcAfIAAAAQgMAMgTAAIAAAAIgCAAg");
	var mask_2_graphics_15 = new cjs.Graphics().p("AONZrIgSgEMgjsgEfQgZAFgQgNIAAAAQgLgIgCgHIAAAAIAAgGIgMhCQgdgZgNgQIAAAAQgHgLgMgCIAAAAIgKAAIkzgZQgJgBgLgDIAAAAQgWgGgHgLIAAAAQgIgKgDgXIAAAAIgCgVIBD/SQAEgSAJgMIAAAAQAGgIAQgEIAAAAIAPgDIAAAAMA4fgK5IARgBQAUADANATIAAAAQANASADAPIAAAAIABAIIAAAAIgBAEIAAAAMgAUAvbIgIAYQgMAbgSAQIAAAAQgSAPgWgCIAAAAIgSgFIqThGQg2AAgVAMIAAAAQgUAMgZAdIAAAAIgVBDIgNAPIgdAeIAAAAQgLANgTAAIAAAAIgCAAg");
	var mask_2_graphics_16 = new cjs.Graphics().p("AOFZcIgRgEMgjZgEbQgYAEgRgNIAAAAQgKgHgCgIIAAAAIAAgFIgMhCQgdgZgMgQIAAAAQgIgKgLgDIAAAAIgKAAIkxgYQgJgBgKgDIAAAAQgWgGgIgLIAAAAQgHgKgEgXIAAAAIgBgUIBC/BQAEgSAJgMIAAAAQAGgHAQgFIAAAAIAOgDIAAAAMA4AgKyIARgBQATADANASIAAAAQANASADAPIAAAAIABAIIAAAAIAAAEIAAAAMgAVAvAIgIAYQgLAbgSAPIAAAAQgSAQgWgCIAAAAIgSgGIqNhFQg2AAgUAMIAAAAQgUAMgZAdIAAAAIgVBCIgNAPIgcAeIAAAAQgMAMgSAAIAAAAIgCAAg");
	var mask_2_graphics_17 = new cjs.Graphics().p("AN9ZOIgRgEMgjFgEZQgYAEgQgMIAAAAQgLgIgCgHIAAAAIABgGIgNhBQgcgYgMgRIAAAAQgIgKgLgCIAAAAIgKAAIkugYQgJgBgKgDIAAAAQgWgHgHgKIAAAAQgIgKgDgXIAAAAIgCgUIBB+vQAFgSAJgMIAAAAQAGgHAPgFIAAAAIAPgDIAAAAMA3ggKsIARgBQATADANASIAAAAQANASADAPIAAAAIABAIIAAAAIgBAEIAAAAMgAUAumIgIAXQgLAbgSAPIAAAAQgSAPgVgCIAAAAIgSgFIqIhFQg1AAgUAMIAAAAQgUAMgZAdIAAAAIgUBBIgNAPIgcAeIAAAAQgMAMgSAAIAAAAIgCAAg");
	var mask_2_graphics_18 = new cjs.Graphics().p("AN1ZAIgRgEMgixgEXQgYAFgQgNIAAAAQgKgHgDgHIAAAAIABgGIgMhBQgdgYgMgQIAAAAQgHgKgLgCIAAAAIgKAAIkrgYQgJgBgLgDIAAAAQgVgGgHgLIAAAAQgIgKgDgWIAAAAIgCgUIBB+eQAEgTAJgLIAAAAQAGgHAPgFIAAAAIAPgDIAAAAMA3BgKmIARgBQATADANASIAAAAQANARADAQIAAAAIABAHIAAAAIgBAEIAAAAMgAUAuMIgIAYQgLAagSAPIAAAAQgRAPgVgCIAAAAIgSgFIqChEQg1AAgUALIAAAAQgUAMgYAdIAAAAIgVBBIgMAPIgcAdIAAAAQgLAMgSAAIAAAAIgDAAg");
	var mask_2_graphics_19 = new cjs.Graphics().p("ANuYyIgRgDMgiegEVQgYAEgQgMIAAAAQgKgHgDgIIAAAAIABgFIgMhAQgcgYgMgQIAAAAQgHgKgMgCIAAAAIgJAAIkpgYQgJgBgKgDIAAAAQgVgGgIgKIAAAAQgHgKgDgXIAAAAIgCgTIBA+OQAEgSAJgLIAAAAQAGgIAPgEIAAAAIAPgDIAAAAMA2jgKhIARAAQATACAMASIAAAAQANASADAPIAAAAIABAHIAAAAIgBAEIAAAAMgAUAtzIgHAXQgLAagSAPIAAAAQgRAQgVgDIAAAAIgSgFIp9hEQg0AAgUAMIAAAAQgTAMgZAcIAAAAIgUBBIgNAOIgbAeIAAAAQgLALgSAAIAAAAIgCAAg");
	var mask_2_graphics_20 = new cjs.Graphics().p("ANmYlIgQgEMgiMgESQgXAEgRgMIAAAAQgKgHgCgHIAAAAIABgGIgMg/QgcgYgMgQIAAAAQgHgKgLgCIAAAAIgKAAIkmgYQgJgBgKgCIAAAAQgVgHgHgKIAAAAQgIgKgDgWIAAAAIgBgTIA/9+QAEgSAJgLIAAAAQAGgHAPgEIAAAAIAOgDIAAAAMA2GgKbIARgBQATADAMARIAAAAQANASACAPIAAAAIABAHIAAAAIAAAEIAAAAMgAUAtaIgIAXQgKAagSAPIAAAAQgRAPgVgCIAAAAIgSgFIp3hEQg0AAgTAMIAAAAQgUAMgYAcIAAAAIgUBAIgMAOIgbAdIAAAAQgMAMgRAAIAAAAIgDAAg");
	var mask_2_graphics_21 = new cjs.Graphics().p("ANfYYIgQgEMgh6gEQQgXAEgQgMIAAAAQgKgHgCgHIAAAAIAAgFIgMg/QgbgYgMgQIAAAAQgHgKgLgCIAAAAIgKAAIkjgXQgJgBgKgDIAAAAQgVgGgHgKIAAAAQgIgKgDgWIAAAAIgBgTIA/9tQAEgSAJgLIAAAAQAFgHAPgFIAAAAIAOgDIAAAAMA1qgKVIAQgBQATADAMARIAAAAQAMASADAOIAAAAIABAIIAAAAIAAAEIAAAAMgAUAtCIgIAWQgKAagSAPIAAAAQgRAPgVgCIAAAAIgRgFIpyhDQgzAAgUALIAAAAQgTAMgYAcIAAAAIgUA/IgMAOIgbAdIAAAAQgLAMgSAAIAAAAIgCAAg");
	var mask_2_graphics_22 = new cjs.Graphics().p("ANYYLIgQgEMghogENQgXAEgQgMIAAAAQgKgHgCgHIAAAAIABgGIgMg+QgcgYgLgPIAAAAQgHgKgLgCIAAAAIgKAAIkhgXQgIgBgLgDIAAAAQgUgGgHgKIAAAAQgIgKgDgWIAAAAIgBgTIA+9dQAEgSAJgLIAAAAQAGgHAOgFIAAAAIAOgCIAAAAMA1NgKQIARgBQASADAMARIAAAAQANARACAPIAAAAIABAHIAAAAIAAAEIAAAAMgAUAsqIgHAXQgLAZgRAPIAAAAQgRAPgVgDIAAAAIgRgEIpthDQgzAAgTAMIAAAAQgTALgYAcIAAAAIgUA/IgMAOIgaAdIAAAAQgMALgRAAIAAAAIgCAAg");
	var mask_2_graphics_23 = new cjs.Graphics().p("ANRX+IgQgDMghWgEMQgXAEgQgLIAAAAQgKgIgCgHIAAAAIABgFIgMg+QgbgXgMgQIAAAAQgHgJgKgCIAAAAIgKAAIkfgXQgIgBgKgDIAAAAQgVgGgHgKIAAAAQgHgKgDgVIAAAAIgCgTIA+9OQAEgSAJgLIAAAAQAGgHAOgEIAAAAIAOgDIAAAAMA0xgKLIAQAAQATACAMARIAAAAQAMARADAPIAAAAIABAHIAAAAIgBAEIAAAAMgATAsTIgIAWQgKAZgRAPIAAAAQgRAPgUgCIAAAAIgSgFIpnhCQgzAAgTALIAAAAQgTAMgYAbIAAAAIgTA+IgMAPIgbAcIAAAAQgLALgRAAIAAAAIgCAAg");
	var mask_2_graphics_24 = new cjs.Graphics().p("ANKXyIgQgEMghEgEJQgXAEgQgMIAAAAQgKgHgCgHIAAAAIABgFIgMg9QgbgXgLgQIAAAAQgHgJgLgCIAAAAIgJAAIkdgXQgIgBgKgDIAAAAQgVgGgHgKIAAAAQgHgJgDgWIAAAAIgBgTIA98/QAEgRAJgLIAAAAQAFgHAPgEIAAAAIANgDIAAAAMA0WgKFIAQgBQATADAMARIAAAAQAMARADAOIAAAAIAAAHIAAAAIAAAEIAAAAMgATAr8IgIAWQgKAZgRAPIAAAAQgRAOgUgCIAAAAIgRgFIpjhBQgyAAgTALIAAAAQgTAMgXAbIAAAAIgTA+IgNAOIgaAcIAAAAQgLALgRAAIAAAAIgCAAg");
	var mask_2_graphics_25 = new cjs.Graphics().p("ANDXmIgQgEMggzgEHQgXAEgQgLIAAAAQgJgIgCgGIAAAAIAAgGIgLg9QgbgWgLgQIAAAAQgHgJgLgCIAAAAIgJAAIkagXQgJgBgKgDIAAAAQgUgGgHgJIAAAAQgHgKgDgVIAAAAIgBgTIA98wQAEgRAIgLIAAAAQAGgHAOgEIAAAAIAOgDIAAAAMAz7gKAIAQgBQASADAMARIAAAAQAMAQADAPIAAAAIAAAHIAAAAIAAADIAAAAMgATArmIgHAWQgLAZgRAOIAAAAQgQAPgUgCIAAAAIgRgFIpehBQgyAAgTALIAAAAQgSAMgYAbIAAAAIgTA9IgMAOIgaAcIAAAAQgLALgQAAIAAAAIgDAAg");
	var mask_2_graphics_26 = new cjs.Graphics().p("AM9XaIgQgDMggjgEGQgXAEgPgLIAAAAQgKgHgCgHIAAAAIABgFIgMg9QgagWgLgPIAAAAQgHgKgLgCIAAAAIgJAAIkYgWQgIgBgKgDIAAAAQgUgGgHgJIAAAAQgHgKgDgVIAAAAIgCgTIA98iQAEgRAIgKIAAAAQAGgHAOgEIAAAAIANgDIAAAAMAzigJ7IAPgBQASADAMAQIAAAAQAMARADAOIAAAAIABAHIAAAAIgBAEIAAAAMgATArQIgHAVQgKAZgRAOIAAAAQgQAPgUgCIAAAAIgRgFIpZhAQgyAAgSALIAAAAQgTALgXAbIAAAAIgTA8IgMAOIgZAcIAAAAQgLALgRAAIAAAAIgCAAg");
	var mask_2_graphics_27 = new cjs.Graphics().p("AM2XPIgPgEMggTgEDQgXAEgPgMIAAAAQgKgHgBgGIAAAAIAAgFIgLg9QgbgWgLgPIAAAAQgHgJgKgCIAAAAIgJAAIkWgXQgIgBgKgCIAAAAQgUgGgHgKIAAAAQgHgJgDgVIAAAAIgBgSIA88UQAEgRAIgLIAAAAQAFgGAPgFIAAAAIANgDIAAAAMAzIgJ2IAPgBQASADAMARIAAAAQAMAQACAOIAAAAIABAHIAAAAIAAAEIAAAAMgATAq6IgHAWQgKAYgRAPIAAAAQgQAOgUgCIAAAAIgRgFIpUhAQgxAAgTALIAAAAQgSALgXAbIAAAAIgTA8IgMAOIgZAcIAAAAQgLALgQAAIAAAAIgDAAg");
	var mask_2_graphics_28 = new cjs.Graphics().p("AMwXDIgPgDMggEgEBQgWADgPgLIAAAAQgKgHgCgGIAAAAIABgGIgLg7QgbgWgKgPIAAAAQgHgKgLgCIAAAAIgJAAIkTgWQgJgBgJgCIAAAAQgUgGgHgKIAAAAQgHgJgDgVIAAAAIgBgSIA78GQAEgRAJgKIAAAAQAFgHAOgEIAAAAIANgDIAAAAMAyvgJxIAQgBQARACAMARIAAAAQAMAQACAOIAAAAIABAHIAAAAIAAAEIAAAAMgATAqlIgHAWQgKAYgRAOIAAAAQgQAOgTgCIAAAAIgRgFIpQg/QgwAAgTALIAAAAQgSALgXAbIAAAAIgSA7IgMAOIgaAbIAAAAQgKALgRAAIAAAAIgCAAg");
	var mask_2_graphics_29 = new cjs.Graphics().p("AMqW4IgPgDI/0kAQgWAEgQgLIAAAAQgJgHgCgGIAAAAIABgFIgMg8QgagWgKgPIAAAAQgHgJgKgCIAAAAIgJAAIkSgWQgIgBgKgCIAAAAQgTgGgHgJIAAAAQgHgKgDgUIAAAAIgBgSIA775QAEgRAIgKIAAAAQAFgHAOgEIAAAAIANgDIAAAAMAyXgJsIAPgBQASADALAQIAAAAQAMAQADAOIAAAAIAAAHIAAAAIAAADIAAAAMgATAqSIgHAVQgKAYgQAOIAAAAQgQAOgUgCIAAAAIgQgFIpLg/QgxAAgSALIAAAAQgSALgXAaIAAAAIgSA8IgMANIgZAbIAAAAQgKALgRAAIAAAAIgCAAg");
	var mask_2_graphics_30 = new cjs.Graphics().p("AMkWtIgPgDI/lj9QgWADgPgLIAAAAQgJgHgCgGIAAAAIAAgFIgLg7QgagWgLgPIAAAAQgGgJgKgCIAAAAIgJAAIkQgWQgIAAgKgDIAAAAQgTgGgHgJIAAAAQgHgJgCgVIAAAAIgCgSIA77rQAEgRAIgKIAAAAQAFgHAOgEIAAAAIANgCIAAAAMAx/gJpIAPAAQARACAMAQIAAAAQALARADANIAAAAIABAHIAAAAIAAAEIAAAAMgATAp9IgHAVQgKAYgQAOIAAAAQgQAOgTgCIAAAAIgRgFIpHg+QgwAAgSALIAAAAQgSAKgWAaIAAAAIgTA7IgLAOIgZAbIAAAAQgLAKgQAAIAAAAIgCAAg");
	var mask_2_graphics_31 = new cjs.Graphics().p("AMeWjIgPgEI/Wj7QgWAEgPgLIAAAAQgJgHgCgHIAAAAIAAgFIgLg6QgZgWgLgOIAAAAQgGgJgLgCIAAAAIgIAAIkOgWQgIgBgKgDIAAAAQgTgFgHgJIAAAAQgHgKgCgUIAAAAIgCgSIA77eQADgRAIgKIAAAAQAGgHANgEIAAAAIANgCIAAAAMAxogJkIAPgBQARADAMAQIAAAAQALAQADAOIAAAAIABAGIAAAAIgBAEIAAAAMgASApqIgHAVQgKAXgQAOIAAAAQgQAOgTgCIAAAAIgQgFIpDg+QgwAAgRALIAAAAQgSALgXAaIAAAAIgSA6IgLANIgZAbIAAAAQgKALgRAAIAAAAIgCAAg");
	var mask_2_graphics_32 = new cjs.Graphics().p("AMZWZIgQgEI/Ij6QgVAEgPgLIAAAAQgJgHgCgGIAAAAIAAgFIgKg6QgagWgKgOIAAAAQgHgJgKgCIAAAAIgJAAIkMgVQgIgBgJgDIAAAAQgTgGgHgJIAAAAQgHgJgCgUIAAAAIgCgSIA67SQAEgQAIgKIAAAAQAFgHAOgEIAAAAIANgCIAAAAMAxQgJgIAQgBQARADALAQIAAAAQALAQADAOIAAAAIABAGIAAAAIgBAEIAAAAMgASApWIgHAVQgJAYgQANIAAAAQgQAOgTgCIAAAAIgQgEIo/g+QgvAAgSALIAAAAQgSAKgWAaIAAAAIgSA6IgLANIgZAbIAAAAQgKALgQAAIAAAAIgCAAg");
	var mask_2_graphics_33 = new cjs.Graphics().p("AMTWPIgPgEI+6j4QgVAEgPgLIAAAAQgJgHgCgGIAAAAIAAgFIgLg6QgZgVgKgOIAAAAQgHgJgKgCIAAAAIgJAAIkKgWQgHAAgKgDIAAAAQgTgGgGgJIAAAAQgHgJgDgUIAAAAIgBgRIA57GQAEgQAIgLIAAAAQAFgGAOgEIAAAAIAMgDIAAAAMAw7gJbIAPgBQARADAMAQIAAAAQALAQACANIAAAAIABAHIAAAAIAAADIAAAAMgASApFIgHAUQgKAYgQANIAAAAQgPAOgTgCIAAAAIgQgFIo7g9QgvAAgRALIAAAAQgSAKgWAaIAAAAIgSA5IgLAOIgZAaIAAAAQgKALgQAAIAAAAIgCAAg");
	var mask_2_graphics_34 = new cjs.Graphics().p("AMOWFIgPgEI+tj2QgVAEgPgLIAAAAQgJgHgBgGIAAAAIAAgFIgLg5QgZgVgKgPIAAAAQgHgJgKgBIAAAAIgIAAIkJgWQgHAAgKgDIAAAAQgSgGgHgJIAAAAQgHgJgDgTIAAAAIgBgSIA566QAEgQAIgKIAAAAQAFgGANgEIAAAAIANgDIAAAAMAwlgJXIAPgBQARADALAPIAAAAQAMAQACAOIAAAAIABAGIAAAAIAAAEIAAAAMgASAoyIgHAUQgKAYgPANIAAAAQgQANgTgBIAAAAIgQgFIo2g8QgvAAgSAKIAAAAQgRAKgWAaIAAAAIgSA5IgLANIgYAaIAAAAQgKALgQAAIAAAAIgCAAg");
	var mask_2_graphics_35 = new cjs.Graphics().p("AMIV7IgOgDI+gj1QgVAEgOgLIAAAAQgJgGgCgHIAAAAIAAgFIgKg4QgZgVgLgPIAAAAQgGgIgKgCIAAAAIgJAAIkGgVQgIgBgJgDIAAAAQgTgFgGgJIAAAAQgHgJgDgUIAAAAIgBgRIA56vQADgQAIgKIAAAAQAFgGAOgEIAAAAIAMgDIAAAAMAwRgJTIAPAAQAQACALAQIAAAAQAMAPACAOIAAAAIABAGIAAAAIAAAEIAAAAMgASAogIgHAVQgKAXgPANIAAAAQgQAOgSgCIAAAAIgQgFIozg8QguAAgSAKIAAAAQgRALgWAZIAAAAIgSA5IgLANIgYAaIAAAAQgKAKgQAAIAAAAIgCAAg");
	var mask_2_graphics_36 = new cjs.Graphics().p("AMDVyIgOgDI+TjzQgVADgOgKIAAAAQgJgHgCgGIAAAAIAAgFIgKg4QgZgVgKgOIAAAAQgHgJgKgCIAAAAIgIAAIkFgVQgHgBgKgCIAAAAQgSgGgHgJIAAAAQgGgJgDgTIAAAAIgBgSIA46jQAEgPAHgKIAAAAQAGgHANgEIAAAAIAMgCIAAAAMAv9gJPIAOgBQARADALAPIAAAAQALAPADAOIAAAAIAAAGIAAAAIAAAEIAAAAMgASAoPIgGAUQgKAXgPAOIAAAAQgQANgSgCIAAAAIgQgEIovg8QguAAgSAKIAAAAQgRALgVAZIAAAAIgSA4IgLANIgYAaIAAAAQgKAKgQAAIAAAAIgCAAg");
	var mask_2_graphics_37 = new cjs.Graphics().p("AL+VpIgOgDI+GjyQgVAEgOgLIAAAAQgJgGgCgGIAAAAIAAgFIgKg4QgZgVgKgOIAAAAQgGgJgKgCIAAAAIgJAAIkDgVQgHAAgJgDIAAAAQgTgFgGgJIAAAAQgHgJgDgTIAAAAIgBgSIA46YQAEgPAHgKIAAAAQAGgHANgEIAAAAIAMgCIAAAAMAvogJLIAPgBQARACALAQIAAAAQALAPACANIAAAAIABAHIAAAAIAAADIAAAAMgASAn/IgHAUQgJAXgQANIAAAAQgPANgSgBIAAAAIgQgFIorg7QguAAgRAKIAAAAQgSAKgVAZIAAAAIgRA4IgLANIgYAaIAAAAQgKAKgQAAIAAAAIgCAAg");
	var mask_2_graphics_38 = new cjs.Graphics().p("AL5VgIgOgDI96jwQgVAEgOgLIAAAAQgJgGgBgGIAAAAIAAgFIgLg4QgYgVgKgNIAAAAQgGgJgKgCIAAAAIgJAAIkBgVQgIgBgJgCIAAAAQgSgGgGgIIAAAAQgHgJgCgTIAAAAIgCgRIA46OQADgQAIgJIAAAAQAFgHANgEIAAAAIANgCIAAAAMAvVgJIIAOAAQARACALAPIAAAAQALAQACANIAAAAIABAGIAAAAIgBAEIAAAAMgARAnuIgHAUQgJAXgPANIAAAAQgQANgSgCIAAAAIgPgEIoog7QguAAgRAKIAAAAQgRAKgVAZIAAAAIgSA4IgLANIgXAZIAAAAQgKAKgPAAIAAAAIgDAAg");
	var mask_2_graphics_39 = new cjs.Graphics().p("AL1VYIgPgDI9ujvQgUAEgOgLIAAAAQgJgGgCgGIAAAAIAAgFIgKg3QgYgVgKgOIAAAAQgHgIgJgCIAAAAIgJAAIj/gVQgIgBgJgCIAAAAQgSgGgHgIIAAAAQgGgJgDgTIAAAAIgBgRIA36DQAEgQAHgKIAAAAQAFgGAOgEIAAAAIAMgCIAAAAMAvCgJEIAPgBQAQADALAPIAAAAQALAPACANIAAAAIABAGIAAAAIAAAEIAAAAMgASAnfIgGAUQgKAWgPANIAAAAQgPANgSgBIAAAAIgPgFIolg6QgtAAgRAKIAAAAQgRAKgVAYIAAAAIgSA4IgLAMIgXAaIAAAAQgKAKgPAAIAAAAIgCAAg");
	var mask_2_graphics_40 = new cjs.Graphics().p("ALwVQIgOgEI9jjtQgUAEgOgKIAAAAQgJgHgCgGIAAAAIABgFIgLg3QgYgUgKgOIAAAAQgGgIgKgCIAAAAIgIAAIj+gVQgIAAgJgDIAAAAQgSgFgGgJIAAAAQgHgJgCgTIAAAAIgCgRIA355QAEgPAIgKIAAAAQAFgGAMgEIAAAAIANgDIAAAAMAuwgJAIAPgBQAQADALAPIAAAAQAKAPADANIAAAAIABAGIAAAAIgBAEIAAAAMgARAnQIgHATQgJAXgPANIAAAAQgPANgSgCIAAAAIgPgEIoig7QgtAAgRAKIAAAAQgQAKgVAZIAAAAIgSA3IgKAMIgYAaIAAAAQgKAKgPAAIAAAAIgCAAg");
	var mask_2_graphics_41 = new cjs.Graphics().p("ALsVIIgOgDI9YjsQgUAEgOgLIAAAAQgJgGgCgGIAAAAIABgFIgLg3QgYgUgKgOIAAAAQgGgIgJgCIAAAAIgJAAIj8gUIgRgEIAAAAQgSgFgGgJIAAAAQgHgIgCgTIAAAAIgBgRIA25vQAEgQAHgJIAAAAQAFgHANgDIAAAAIAMgDIAAAAMAufgI9IAPgBQAQADAKAPIAAAAQALAPADANIAAAAIAAAGIAAAAIAAADIAAAAMgARAnCIgHATQgJAWgPANIAAAAQgPANgSgCIAAAAIgPgEIoeg6QgtAAgRAKIAAAAQgQAKgVAZIAAAAIgRA2IgLANIgXAZIAAAAQgKAKgPAAIAAAAIgCAAg");
	var mask_2_graphics_42 = new cjs.Graphics().p("ALoVAIgPgDI9MjqQgVADgOgKIAAAAQgIgHgCgGIAAAAIAAgEIgKg3QgYgUgKgNIAAAAQgGgJgJgCIAAAAIgIAAIj8gUIgQgDIAAAAQgSgFgGgJIAAAAQgHgJgCgSIAAAAIgCgRIA35mQADgQAIgJIAAAAQAFgGANgEIAAAAIAMgDIAAAAMAuOgI5IAOgBQAQACALAPIAAAAQAKAPADANIAAAAIABAGIAAAAIgBAEIAAAAMgARAmzIgGATQgKAWgOANIAAAAQgPANgSgCIAAAAIgPgEIobg6QgtAAgRAKIAAAAQgQAKgVAYIAAAAIgRA3IgLAMIgXAZIAAAAQgJAKgPAAIAAAAIgCAAg");
	var mask_2_graphics_43 = new cjs.Graphics().p("ALkU5IgPgEI9CjoQgUADgOgKIAAAAQgJgHgBgGIAAAAIAAgEIgKg2QgYgUgKgOIAAAAQgGgIgJgCIAAAAIgJAAIj5gUIgRgDIAAAAQgRgGgHgIIAAAAQgGgJgDgSIAAAAIgBgRIA25dQAEgPAHgKIAAAAQAFgGANgEIAAAAIAMgCIAAAAMAt9gI3IAPgBQAQADAKAPIAAAAQALAOACANIAAAAIABAGIAAAAIAAAEIAAAAMgARAmlIgHAUQgJAWgPAMIAAAAQgPANgRgCIAAAAIgPgEIoYg5QgtAAgQAKIAAAAQgRAKgUAYIAAAAIgRA2IgLAMIgXAZIAAAAQgKAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_44 = new cjs.Graphics().p("ALgUyIgOgEI85jnQgUADgOgKIAAAAQgIgGgCgGIAAAAIAAgFIgKg2QgXgUgKgNIAAAAQgGgJgKgBIAAAAIgIAAIj4gUIgRgEIAAAAQgRgFgHgIIAAAAQgGgJgCgSIAAAAIgCgRIA25UQAEgPAHgKIAAAAQAFgGANgEIAAAAIALgCIAAAAMAtvgI0IAOgBQAPADALAPIAAAAQAKAOADANIAAAAIABAGIAAAAIgBAEIAAAAMgARAmYIgGATQgJAWgPANIAAAAQgPAMgRgBIAAAAIgPgFIoVg5QgsAAgRAKIAAAAQgQAKgVAYIAAAAIgRA2IgKAMIgXAZIAAAAQgKAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_45 = new cjs.Graphics().p("ALcUrIgOgEI8vjmQgUADgOgKIAAAAQgIgGgCgGIAAAAIAAgEIgKg2QgXgUgKgNIAAAAQgGgJgJgBIAAAAIgIAAIj4gUIgQgDIAAAAQgRgGgHgIIAAAAQgGgJgCgSIAAAAIgCgQIA25MQADgQAIgJIAAAAQAEgGANgEIAAAAIAMgCIAAAAMAtfgIxIAOgBQAQADAKAOIAAAAQALAPACANIAAAAIABAGIAAAAIgBADIAAAAMgAQAmMIgHATQgJAWgPAMIAAAAQgOANgSgCIAAAAIgOgEIoTg5QgsAAgQAKIAAAAQgRAKgUAYIAAAAIgRA1IgKAMIgXAZIAAAAQgKAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_46 = new cjs.Graphics().p("ALYUkIgOgDI8mjmQgTAEgOgKIAAAAQgIgGgCgGIAAAAIAAgFIgKg1QgXgUgKgNIAAAAQgGgJgJgBIAAAAIgIAAIj2gUIgQgDIAAAAQgSgFgGgJIAAAAQgGgIgDgTIAAAAIgBgQIA15EQAEgPAHgJIAAAAQAFgGAMgEIAAAAIAMgCIAAAAMAtQgIuIAOgBQAQACAKAPIAAAAQALAPACAMIAAAAIABAGIAAAAIAAAEIAAAAMgARAl/IgGATQgJAWgPAMIAAAAQgPANgRgCIAAAAIgPgEIoQg5QgrAAgQAKIAAAAQgRAKgUAXIAAAAIgRA2IgKAMIgXAYIAAAAQgJAKgPAAIAAAAIgCAAg");
	var mask_2_graphics_47 = new cjs.Graphics().p("ALVUeIgOgEI8djkQgUAEgNgKIAAAAQgJgHgCgFIAAAAIABgFIgKg1QgXgUgKgNIAAAAQgGgIgJgCIAAAAIgIAAIj1gUIgQgDIAAAAQgRgFgHgIIAAAAQgGgJgCgSIAAAAIgCgQIA148QAEgPAHgKIAAAAQAFgFAMgEIAAAAIAMgDIAAAAMAtCgIrIAOgBQAQADAKAOIAAAAQALAPACAMIAAAAIABAGIAAAAIgBAEIAAAAMgAQAlzIgHATQgJAWgOAMIAAAAQgPANgRgCIAAAAIgPgEIoNg4QgrAAgRAJIAAAAQgQAKgUAYIAAAAIgRA1IgKAMIgWAYIAAAAQgKAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_48 = new cjs.Graphics().p("ALRUXIgOgDI8UjjQgUAEgNgKIAAAAQgIgHgCgFIAAAAIAAgFIgKg1QgXgTgKgNIAAAAQgFgJgKgBIAAAAIgIAAIjzgUIgQgDIAAAAQgRgFgHgJIAAAAQgGgIgCgSIAAAAIgCgQIA141QAEgPAHgJIAAAAQAFgGAMgEIAAAAIAMgCIAAAAMAs0gIpIAOgBQAQADAKAOIAAAAQAKAPADAMIAAAAIABAGIAAAAIgBAEIAAAAMgAQAloIgHATQgIAVgPAMIAAAAQgOANgSgCIAAAAIgOgEIoLg4QgrAAgQAKIAAAAQgRAJgUAYIAAAAIgQA1IgLAMIgWAYIAAAAQgJAKgPAAIAAAAIgCgBg");
	var mask_2_graphics_49 = new cjs.Graphics().p("ALOUSIgOgDI8MjjQgUAEgNgKIAAAAQgIgGgCgGIAAAAIAAgFIgKg0QgXgUgJgNIAAAAQgGgIgJgCIAAAAIgIAAIjzgTIgQgDIAAAAQgRgFgGgJIAAAAQgGgIgDgSIAAAAIgBgQIA14uQADgPAHgJIAAAAQAFgGAMgDIAAAAIAMgDIAAAAMAsogImIAOgBQAPADAKAOIAAAAQALAPACAMIAAAAIABAGIAAAAIgBADIAAAAMgAQAldIgGATQgJAWgPAMIAAAAQgOAMgRgBIAAAAIgPgEIoIg4QgrAAgQAKIAAAAQgQAJgUAXIAAAAIgRA1IgKAMIgWAYIAAAAQgKAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_50 = new cjs.Graphics().p("ALLUMIgOgDI8EjhQgUADgNgKIAAAAQgIgGgCgGIAAAAIAAgEIgKg0QgWgUgKgNIAAAAQgGgIgJgCIAAAAIgIAAIjygTIgPgDIAAAAQgRgFgHgJIAAAAQgGgIgCgSIAAAAIgBgQIA04nQADgOAHgKIAAAAQAFgFANgEIAAAAIALgDIAAAAMAscgIjIANgBQAQACAKAPIAAAAQAKAOADAMIAAAAIAAAGIAAAAIAAAEIAAAAMgAQAlTIgHASQgIAVgPANIAAAAQgOAMgRgCIAAAAIgPgEIoGg3QgrAAgQAKIAAAAQgQAJgUAXIAAAAIgQA1IgKAMIgXAXIAAAAQgJAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_51 = new cjs.Graphics().p("ALIUHIgOgDI79jhQgTAEgNgKIAAAAQgJgGgBgGIAAAAIAAgEIgKg0QgXgUgJgNIAAAAQgGgIgJgCIAAAAIgIAAIjxgTIgPgDIAAAAQgRgFgGgIIAAAAQgHgJgCgSIAAAAIgBgQIA04gQADgOAHgKIAAAAQAFgFAMgEIAAAAIAMgDIAAAAMAsQgIhIANgBQAQADAKAOIAAAAQAKAOACAMIAAAAIABAGIAAAAIAAAEIAAAAMgARAlJIgGASQgIAWgPAMIAAAAQgOAMgRgCIAAAAIgOgEIoFg3QgqAAgQAKIAAAAQgQAJgUAXIAAAAIgQA0IgKAMIgXAYIAAAAQgJAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_52 = new cjs.Graphics().p("ALFUCIgNgDI72jgQgUAEgNgKIAAAAQgIgGgCgGIAAAAIAAgFIgJgzQgXgUgKgNIAAAAQgFgIgJgBIAAAAIgIAAIjwgUIgPgDIAAAAQgRgFgHgIIAAAAQgGgIgCgSIAAAAIgBgQIAz4aQAEgPAHgJIAAAAQAFgGAMgDIAAAAIALgDIAAAAMAsFgIfIAOgBQAPADAKAOIAAAAQAKAOADAMIAAAAIAAAGIAAAAIAAAEIAAAAMgAQAk/IgGATQgJAVgOAMIAAAAQgPAMgRgBIAAAAIgOgEIoCg3QgqAAgQAJIAAAAQgQAKgUAXIAAAAIgQA0IgKALIgWAYIAAAAQgKAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_53 = new cjs.Graphics().p("ALCT9IgNgDI7vjfQgUAEgNgKIAAAAQgIgGgCgGIAAAAIABgEIgKg0QgXgTgJgNIAAAAQgGgIgJgCIAAAAIgIAAIjvgTIgPgDIAAAAQgRgFgGgIIAAAAQgGgIgCgSIAAAAIgCgQIA04UQADgPAHgJIAAAAQAFgGAMgDIAAAAIAMgDIAAAAMAr6gIdIANgBQAPACALAPIAAAAQAKAOACAMIAAAAIABAGIAAAAIgBADIAAAAMgAQAk3IgGATQgJAVgOAMIAAAAQgOAMgRgCIAAAAIgOgEIoAg3QgrAAgPAKIAAAAQgQAJgUAXIAAAAIgQA0IgKAMIgWAXIAAAAQgJAKgPAAIAAAAIgCAAg");
	var mask_2_graphics_54 = new cjs.Graphics().p("ALAT4IgOgDI7pjeQgTAEgNgKIAAAAQgIgGgCgGIAAAAIABgEIgKg0QgXgTgJgMIAAAAQgGgJgJgBIAAAAIgIAAIjtgTIgQgDIAAAAQgRgGgGgIIAAAAQgGgIgCgRIAAAAIgCgQIA04PQADgOAHgJIAAAAQAFgGAMgEIAAAAIAMgCIAAAAMArwgIcIANAAQAPACAKAOIAAAAQAKAOADAMIAAAAIABAGIAAAAIgBAEIAAAAMgAQAkuIgGASQgJAVgOAMIAAAAQgOANgRgCIAAAAIgOgEIn/g3QgqAAgPAKIAAAAQgQAJgUAXIAAAAIgQA0IgKALIgWAYIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_55 = new cjs.Graphics().p("AK+T0IgOgDI7jjdQgTADgNgJIAAAAQgIgGgCgGIAAAAIABgFIgKgzQgXgTgJgNIAAAAQgGgIgJgBIAAAAIgIAAIjtgUIgPgDIAAAAQgRgFgGgIIAAAAQgGgIgCgRIAAAAIgCgQIA04KQADgOAHgJIAAAAQAFgGAMgDIAAAAIALgDIAAAAMArngIZIANgBQAPACAKAOIAAAAQAKAOADANIAAAAIABAFIAAAAIgBAEIAAAAMgAQAkmIgGATQgJAUgOAMIAAAAQgOANgRgCIAAAAIgOgEIn8g3QgqAAgQAKIAAAAQgQAJgTAXIAAAAIgQAzIgLAMIgVAYIAAAAQgJAJgPAAIAAAAIgBAAg");
	var mask_2_graphics_56 = new cjs.Graphics().p("AK7TwIgNgDI7djcQgUADgNgKIAAAAQgIgGgBgFIAAAAIAAgFIgKgzQgWgTgJgNIAAAAQgGgIgJgBIAAAAIgIAAIjsgTIgPgDIAAAAQgRgFgGgIIAAAAQgGgIgDgSIAAAAIgBgQIAz4EQAEgPAHgJIAAAAQAEgFAMgEIAAAAIAMgCIAAAAMArdgIYIAOgBQAPACAKAOIAAAAQAKAOACAMIAAAAIABAGIAAAAIgBADIAAAAMgAQAkgIgGASQgIAVgOAMIAAAAQgOAMgRgCIAAAAIgOgEIn7g2QgqAAgQAJIAAAAQgPAKgUAWIAAAAIgQAzIgKAMIgWAYIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_57 = new cjs.Graphics().p("AK5TsIgNgDI7YjbQgTADgNgKIAAAAQgIgGgCgFIAAAAIAAgFIgJgzQgXgTgJgMIAAAAQgGgIgJgCIAAAAIgHAAIjsgTIgPgDIAAAAQgRgFgGgIIAAAAQgGgIgCgSIAAAAIgCgPIAz4AQAEgPAHgJIAAAAQAEgFAMgEIAAAAIAMgCIAAAAMArVgIXIANAAQAPACAKAOIAAAAQAKAOADAMIAAAAIABAGIAAAAIgBADIAAAAMgAQAkYIgGATQgJAUgOAMIAAAAQgOAMgQgBIAAAAIgOgEIn6g2QgpAAgQAJIAAAAQgQAJgTAXIAAAAIgQAzIgKAMIgWAXIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_58 = new cjs.Graphics().p("AK3TpIgNgDI7TjbQgTADgNgKIAAAAQgIgGgCgFIAAAAIABgFIgKgyQgWgTgKgNIAAAAQgFgIgJgCIAAAAIgIAAIjrgTIgPgDIAAAAQgRgFgGgIIAAAAQgGgIgCgRIAAAAIgBgQIAy37QAEgPAHgJIAAAAQAEgFAMgEIAAAAIAMgCIAAAAMArNgIVIAOgBQAOADAKAOIAAAAQAKAOADAMIAAAAIAAAFIAAAAIAAADIAAAAMgAQAkSIgGASQgJAVgNAMIAAAAQgOAMgRgCIAAAAIgOgEIn4g2QgqAAgPAKIAAAAQgQAJgTAXIAAAAIgQAyIgKAMIgWAXIAAAAQgJAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_59 = new cjs.Graphics().p("AK1TlIgNgDI7PjaQgSADgNgJIAAAAQgIgGgCgGIAAAAIAAgEIgJgzQgWgTgKgMIAAAAQgFgIgJgCIAAAAIgIAAIjqgTIgQgDIAAAAQgQgFgGgIIAAAAQgGgIgCgRIAAAAIgCgQIAz34QADgOAHgJIAAAAQAFgFAMgEIAAAAIALgCIAAAAMArHgIUIANAAQAPACAKAOIAAAAQAKAOACAMIAAAAIABAFIAAAAIgBAEIAAAAMgAQAkLIgGASQgIAVgOAMIAAAAQgOAMgRgCIAAAAIgOgEIn2g2QgqAAgPAKIAAAAQgQAJgTAXIAAAAIgQAyIgKAMIgWAXIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_60 = new cjs.Graphics().p("AK0TiIgNgDI7LjZQgTADgNgKIAAAAQgIgGgBgFIAAAAIAAgFIgKgyQgWgTgJgNIAAAAQgGgIgJgBIAAAAIgHAAIjqgTIgPgDIAAAAQgRgFgGgIIAAAAQgGgIgCgRIAAAAIgBgQIAy30QAEgOAHgJIAAAAQAEgGAMgDIAAAAIALgDIAAAAMArAgISIANAAQAPACAKAOIAAAAQAKAOADAMIAAAAIAAAFIAAAAIAAADIAAAAMgAQAkHIgGASQgJAUgNAMIAAAAQgOAMgRgCIAAAAIgOgEIn1g1QgqAAgPAJIAAAAQgQAJgTAXIAAAAIgQAyIgKAMIgVAXIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_61 = new cjs.Graphics().p("AKyTgIgNgDI7HjaQgSAEgNgKIAAAAQgIgGgCgGIAAAAIAAgEIgJgyQgWgTgKgNIAAAAQgFgIgJgBIAAAAIgIAAIjpgTIgPgDIAAAAQgRgFgGgIIAAAAQgFgIgDgRIAAAAIgBgQIAy3wQAEgPAHgJIAAAAQAEgFAMgEIAAAAIALgCIAAAAMAq6gIRIANgBQAPADAKANIAAAAQAKAOACAMIAAAAIABAGIAAAAIAAADIAAAAMgAQAkBIgGASQgJAVgOAMIAAAAQgNALgRgBIAAAAIgOgEIn0g2QgqAAgPAKIAAAAQgQAJgTAWIAAAAIgQAzIgKALIgVAXIAAAAQgJAKgOAAIAAAAIgCAAg");
	var mask_2_graphics_62 = new cjs.Graphics().p("AKxTdIgNgDI7EjZQgSAEgNgKIAAAAQgIgGgCgGIAAAAIABgEIgKgyQgWgTgJgNIAAAAQgGgHgJgCIAAAAIgHAAIjpgTIgPgDIAAAAQgRgFgGgIIAAAAQgGgIgCgRIAAAAIgBgPIAy3uQADgOAHgJIAAAAQAFgGAMgDIAAAAIALgDIAAAAMAq0gIQIAOAAQAOACAKAOIAAAAQAKAOADAMIAAAAIAAAFIAAAAIAAADIAAAAMgAQAj9IgGASQgIAUgOAMIAAAAQgOAMgRgCIAAAAIgNgDIn0g2QgpAAgQAJIAAAAQgPAKgTAWIAAAAIgQAyIgKAMIgVAXIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_63 = new cjs.Graphics().p("AKwTbIgNgDI7BjZQgSAEgNgKIAAAAQgIgGgCgFIAAAAIABgFIgKgyQgWgTgJgMIAAAAQgGgIgJgCIAAAAIgHAAIjpgSIgPgDIAAAAQgQgFgGgIIAAAAQgGgIgCgSIAAAAIgCgPIAz3rQADgOAHgJIAAAAQAEgFAMgEIAAAAIALgCIAAAAMAqwgIPIANgBQAPACAKAOIAAAAQAKAOACAMIAAAAIABAFIAAAAIgBAEIAAAAMgAQAj4IgFASQgJAUgOAMIAAAAQgOAMgQgCIAAAAIgOgEInzg1QgpAAgPAJIAAAAQgQAKgTAWIAAAAIgPAyIgKAMIgWAXIAAAAQgJAJgNAAIAAAAIgCAAg");
	var mask_2_graphics_64 = new cjs.Graphics().p("AKvTZIgOgDI69jYQgTADgNgJIAAAAQgHgGgCgGIAAAAIAAgEIgJgyQgWgTgJgNIAAAAQgGgHgJgCIAAAAIgHAAIjpgTIgPgDIAAAAQgQgFgGgIIAAAAQgGgHgCgSIAAAAIgBgPIAy3pQADgOAHgJIAAAAQAFgFALgEIAAAAIAMgCIAAAAMAqrgIOIANgBQAPACAKAOIAAAAQAJAOADAMIAAAAIAAAFIAAAAIAAADIAAAAMgAQAj1IgGASQgIAVgOALIAAAAQgOAMgQgBIAAAAIgOgEInyg2QgpAAgPAKIAAAAQgQAJgTAWIAAAAIgQAyIgJAMIgWAXIAAAAQgJAJgNAAIAAAAIgCAAg");
	var mask_2_graphics_65 = new cjs.Graphics().p("AKuTXIgNgDI68jYQgSAEgNgKIAAAAQgIgGgCgFIAAAAIABgFIgKgyQgWgSgJgNIAAAAQgFgIgJgBIAAAAIgIAAIjogTIgPgDIAAAAQgQgFgGgIIAAAAQgGgIgCgRIAAAAIgBgPIAy3nQADgOAHgJIAAAAQAEgFAMgEIAAAAIALgCIAAAAMAqogIOIANAAQAPACAKAOIAAAAQAJANADAMIAAAAIAAAGIAAAAIAAADIAAAAMgAQAjyIgGASQgIAUgOAMIAAAAQgOAMgQgCIAAAAIgOgEInxg1QgpAAgPAJIAAAAQgQAJgTAXIAAAAIgQAyIgJALIgWAXIAAAAQgJAJgNAAIAAAAIgCAAg");
	var mask_2_graphics_66 = new cjs.Graphics().p("AKtTWIgNgDI65jYQgTADgNgJIAAAAQgIgGgBgFIAAAAIAAgFIgJgyQgWgSgKgNIAAAAQgFgIgJgBIAAAAIgIAAIjngTIgPgDIAAAAQgQgFgGgIIAAAAQgGgIgDgRIAAAAIgBgPIAy3lQAEgOAGgJIAAAAQAFgGAMgDIAAAAIALgCIAAAAMAqkgINIANgBQAPACAKAOIAAAAQAKAOACAMIAAAAIABAFIAAAAIgBADIAAAAMgAPAjvIgGASQgJAVgNAMIAAAAQgOALgRgBIAAAAIgNgEInxg1QgpAAgPAJIAAAAQgQAJgTAWIAAAAIgPAyIgKAMIgWAXIAAAAQgIAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_67 = new cjs.Graphics().p("AKsTVIgNgDI63jYQgTAEgNgKIAAAAQgIgGgBgFIAAAAIAAgFIgJgyQgWgSgKgNIAAAAQgFgIgJgBIAAAAIgHAAIjogTIgPgDIAAAAQgQgFgGgIIAAAAQgGgHgCgSIAAAAIgBgPIAy3jQADgPAHgIIAAAAQAEgGAMgEIAAAAIALgCIAAAAMAqigIMIANgBQAPACAKAOIAAAAQAJAOADAMIAAAAIAAAFIAAAAIAAAEIAAAAMgAQAjsIgGASQgIAVgOALIAAAAQgOAMgQgBIAAAAIgOgEInwg1QgpAAgPAJIAAAAQgPAJgTAWIAAAAIgQAyIgKAMIgVAXIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_68 = new cjs.Graphics().p("AKsTUIgNgDI63jXQgSADgNgKIAAAAQgIgGgBgFIAAAAIAAgEIgKgyQgWgTgJgMIAAAAQgFgIgJgCIAAAAIgIAAIjngTIgPgDIAAAAQgQgEgGgIIAAAAQgGgIgCgRIAAAAIgBgQIAy3iQADgOAHgJIAAAAQAEgFAMgEIAAAAIALgCIAAAAMAqggIMIANgBQAPACAKAOIAAAAQAJAOADAMIAAAAIAAAFIAAAAIAAADIAAAAMgAQAjsIgGASQgIAUgOAMIAAAAQgOALgQgBIAAAAIgOgEInvg1QgpAAgQAJIAAAAQgPAJgTAWIAAAAIgQAyIgJAMIgWAXIAAAAQgJAJgNAAIAAAAIgCAAg");
	var mask_2_graphics_69 = new cjs.Graphics().p("AKrTTIgNgDI61jXQgTADgMgJIAAAAQgIgGgCgGIAAAAIAAgEIgJgyQgWgTgJgMIAAAAQgGgIgIgBIAAAAIgIAAIjngTIgPgDIAAAAQgQgFgGgIIAAAAQgGgIgCgRIAAAAIgCgPIAy3iQAEgOAGgIIAAAAQAFgGAMgEIAAAAIALgCIAAAAMAqegIMIANAAQAPACAKAOIAAAAQAKANACAMIAAAAIABAGIAAAAIgBADIAAAAMgAPAjqIgGASQgJAUgOAMIAAAAQgNAMgRgCIAAAAIgNgEInwg1QgpAAgPAJIAAAAQgPAKgTAWIAAAAIgQAyIgKALIgVAXIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_70 = new cjs.Graphics().p("AKrTTIgNgDI61jXQgSADgNgKIAAAAQgIgFgCgGIAAAAIABgEIgKgyQgWgTgJgMIAAAAQgFgIgJgCIAAAAIgIAAIjngSIgPgDIAAAAQgQgFgGgIIAAAAQgGgIgCgRIAAAAIgBgPIAy3hQADgOAHgJIAAAAQAEgGAMgDIAAAAIALgDIAAAAMAqegILIANgBQAPACAJAOIAAAAQAKAOACAMIAAAAIABAFIAAAAIAAADIAAAAMgAQAjqIgGASQgIAUgOAMIAAAAQgOALgQgBIAAAAIgOgEInvg1QgpAAgPAJIAAAAQgQAJgTAWIAAAAIgPAyIgKAMIgVAXIAAAAQgJAJgOAAIAAAAIgCAAg");
	var mask_2_graphics_71 = new cjs.Graphics().p("AKrTTIgNgDI61jXQgSADgNgKIAAAAQgIgGgBgFIAAAAIAAgEIgKgyQgVgTgKgMIAAAAQgFgIgJgCIAAAAIgHAAIjngSIgPgDIAAAAQgRgFgGgIIAAAAQgFgIgDgRIAAAAIgBgQIAy3gQADgOAHgJIAAAAQAFgGALgDIAAAAIALgDIAAAAMAqegILIANgBQAOADAKANIAAAAQAKAOACAMIAAAAIABAFIAAAAIAAAEIAAAAMgAQAjpIgGARQgIAVgOALIAAAAQgOAMgQgBIAAAAIgOgEInvg1QgpAAgPAJIAAAAQgQAJgTAWIAAAAIgPAyIgKAMIgVAXIAAAAQgJAJgOAAIAAAAIgCAAg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:289.8073,y:267.7032}).wait(1).to({graphics:mask_2_graphics_1,x:286.2506,y:267.7671}).wait(1).to({graphics:mask_2_graphics_2,x:282.7449,y:267.8305}).wait(1).to({graphics:mask_2_graphics_3,x:279.2887,y:267.8934}).wait(1).to({graphics:mask_2_graphics_4,x:275.8839,y:267.955}).wait(1).to({graphics:mask_2_graphics_5,x:272.529,y:268.0149}).wait(1).to({graphics:mask_2_graphics_6,x:269.2249,y:268.0747}).wait(1).to({graphics:mask_2_graphics_7,x:265.9711,y:268.1336}).wait(1).to({graphics:mask_2_graphics_8,x:262.7677,y:268.1912}).wait(1).to({graphics:mask_2_graphics_9,x:259.6151,y:268.2488}).wait(1).to({graphics:mask_2_graphics_10,x:256.5125,y:268.3046}).wait(1).to({graphics:mask_2_graphics_11,x:253.4605,y:268.3594}).wait(1).to({graphics:mask_2_graphics_12,x:250.4586,y:268.4143}).wait(1).to({graphics:mask_2_graphics_13,x:247.5075,y:268.4673}).wait(1).to({graphics:mask_2_graphics_14,x:244.607,y:268.52}).wait(1).to({graphics:mask_2_graphics_15,x:241.7565,y:268.5709}).wait(1).to({graphics:mask_2_graphics_16,x:238.9571,y:268.6217}).wait(1).to({graphics:mask_2_graphics_17,x:236.2077,y:268.6715}).wait(1).to({graphics:mask_2_graphics_18,x:233.5087,y:268.7202}).wait(1).to({graphics:mask_2_graphics_19,x:230.8601,y:268.7683}).wait(1).to({graphics:mask_2_graphics_20,x:228.2623,y:268.8151}).wait(1).to({graphics:mask_2_graphics_21,x:225.7148,y:268.8609}).wait(1).to({graphics:mask_2_graphics_22,x:223.2174,y:268.9059}).wait(1).to({graphics:mask_2_graphics_23,x:220.7712,y:268.95}).wait(1).to({graphics:mask_2_graphics_24,x:218.3746,y:268.9932}).wait(1).to({graphics:mask_2_graphics_25,x:216.029,y:269.0359}).wait(1).to({graphics:mask_2_graphics_26,x:213.7337,y:269.0773}).wait(1).to({graphics:mask_2_graphics_27,x:211.4885,y:269.1178}).wait(1).to({graphics:mask_2_graphics_28,x:209.2945,y:269.1578}).wait(1).to({graphics:mask_2_graphics_29,x:207.1505,y:269.1961}).wait(1).to({graphics:mask_2_graphics_30,x:205.0567,y:269.2342}).wait(1).to({graphics:mask_2_graphics_31,x:203.0138,y:269.2711}).wait(1).to({graphics:mask_2_graphics_32,x:201.0212,y:269.3071}).wait(1).to({graphics:mask_2_graphics_33,x:199.0787,y:269.3422}).wait(1).to({graphics:mask_2_graphics_34,x:197.187,y:269.3764}).wait(1).to({graphics:mask_2_graphics_35,x:195.346,y:269.4092}).wait(1).to({graphics:mask_2_graphics_36,x:193.5552,y:269.4416}).wait(1).to({graphics:mask_2_graphics_37,x:191.8147,y:269.4735}).wait(1).to({graphics:mask_2_graphics_38,x:190.1245,y:269.5037}).wait(1).to({graphics:mask_2_graphics_39,x:188.485,y:269.5338}).wait(1).to({graphics:mask_2_graphics_40,x:186.896,y:269.5621}).wait(1).to({graphics:mask_2_graphics_41,x:185.3573,y:269.59}).wait(1).to({graphics:mask_2_graphics_42,x:183.8693,y:269.617}).wait(1).to({graphics:mask_2_graphics_43,x:182.4313,y:269.6426}).wait(1).to({graphics:mask_2_graphics_44,x:181.0445,y:269.6678}).wait(1).to({graphics:mask_2_graphics_45,x:179.7072,y:269.6917}).wait(1).to({graphics:mask_2_graphics_46,x:178.4211,y:269.7151}).wait(1).to({graphics:mask_2_graphics_47,x:177.1854,y:269.7375}).wait(1).to({graphics:mask_2_graphics_48,x:175.9995,y:269.7587}).wait(1).to({graphics:mask_2_graphics_49,x:174.8644,y:269.7794}).wait(1).to({graphics:mask_2_graphics_50,x:173.78,y:269.7991}).wait(1).to({graphics:mask_2_graphics_51,x:172.7455,y:269.818}).wait(1).to({graphics:mask_2_graphics_52,x:171.7618,y:269.8356}).wait(1).to({graphics:mask_2_graphics_53,x:170.8287,y:269.8527}).wait(1).to({graphics:mask_2_graphics_54,x:169.9458,y:269.868}).wait(1).to({graphics:mask_2_graphics_55,x:169.1134,y:269.8833}).wait(1).to({graphics:mask_2_graphics_56,x:168.3318,y:269.8977}).wait(1).to({graphics:mask_2_graphics_57,x:167.6004,y:269.9108}).wait(1).to({graphics:mask_2_graphics_58,x:166.9189,y:269.9233}).wait(1).to({graphics:mask_2_graphics_59,x:166.2886,y:269.9346}).wait(1).to({graphics:mask_2_graphics_60,x:165.7086,y:269.9449}).wait(1).to({graphics:mask_2_graphics_61,x:165.1788,y:269.9544}).wait(1).to({graphics:mask_2_graphics_62,x:164.6993,y:269.9629}).wait(1).to({graphics:mask_2_graphics_63,x:164.2707,y:269.971}).wait(1).to({graphics:mask_2_graphics_64,x:163.8927,y:269.9778}).wait(1).to({graphics:mask_2_graphics_65,x:163.5646,y:269.9836}).wait(1).to({graphics:mask_2_graphics_66,x:163.287,y:269.9886}).wait(1).to({graphics:mask_2_graphics_67,x:163.0597,y:269.993}).wait(1).to({graphics:mask_2_graphics_68,x:162.8834,y:269.9957}).wait(1).to({graphics:mask_2_graphics_69,x:162.7574,y:269.998}).wait(1).to({graphics:mask_2_graphics_70,x:162.6818,y:269.9994}).wait(1).to({graphics:mask_2_graphics_71,x:162.6566,y:269.9021}).wait(75));

	// HL
	this.instance_4 = new lib.HL();
	this.instance_4.setTransform(391.9,291.25,1,1,0,0,0,297.9,0);
	this.instance_4.alpha = 0.5;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:494.95,y:288},96,cjs.Ease.quadOut).wait(50));

	// PLATE
	this.instance_5 = new lib.PLATE();
	this.instance_5.setTransform(295.25,273.25);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({regY:0.1,scaleX:0.6531,scaleY:0.6531,x:165.7,y:274.15},71,cjs.Ease.quadOut).wait(75));

	// BKGD
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(146));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(40.3,300,660,300);
// library properties:
lib.properties = {
	id: '0E11E9F5D49240C6BBEEAC80F63F5DAC',
	width: 300,
	height: 600,
	fps: 24,
	color: "#CCCCCC",
	opacity: 1.00,
	manifest: [
		{src:"images/REV659_Wave2_Awareness_300x600_atlas_1.png", id:"REV659_Wave2_Awareness_300x600_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0E11E9F5D49240C6BBEEAC80F63F5DAC'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;